(function(g){var window=this;'use strict';var y$k=function(G,B,a){g.v(function(V){G.j=g.bm(B,a);g.pV(V)})},wh=function(G){G.isActive()||G.start()},c$s=function(G,B){return B?G.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},nj8=function(G){return g.YF(G)||G.S("web_enable_caption_language_preference_stickiness")},fQh=function(G,B){var a=new g.Nk;
a.languageCode=G.languageCode;a.languageName=G.languageName;a.name=G.name;a.displayName=G.displayName;a.kind=G.kind;a.isDefault=!1;a.j=G.j;a.isTranslateable=G.isTranslateable;a.vssId=G.vssId;a.url=G.url;a.translationLanguage=B;G.xtags&&(a.xtags=G.xtags);G.captionId&&(a.captionId=G.captionId);return a},Ho7=function(G,B){var a,V,x;
return g.v(function(h){if(h.j==1)return a=G+"|"+B,g.f(h,g.PL(),2);if(h.j!=3){V=h.X;if(!V)throw g.pN("gct");return g.f(h,g.H_(V),3)}x=h.X;return h.return(x.get("captions",a))})},vj3=function(G,B,a){Ho7(G,B).then(function(V){V&&a(V.trackData,new g.Nk(V.metadata))})},R49=function(G){if(!D6a.test(G))throw Error("'"+G+"' is not a valid hex color");
G.length==4&&(G=G.replace(Sua,"#$1$1$2$2$3$3"));G=G.toLowerCase();G=parseInt(G.slice(1),16);return[G>>16,G>>8&255,G&255]},Zoh=function(){var G=void 0;
G=G===void 0?{}:G;var B="suggest_correction"in g.x23?g.x23.suggest_correction:"Edit caption";B=B||"";var a={},V;for(V in G){a={Ma:a.Ma};a.Ma=V;var x=function(h){return function(){return String(G[h.Ma])}}(a);
B=B.replace(new RegExp("\\$\\{"+a.Ma+"\\}","gi"),x);B=B.replace(new RegExp("\\$"+a.Ma,"gi"),x)}return B},r$a=function(){return g.SL("yt-player-caption-display-settings")},K3=function(){this.segments=[]},$6h=function(G,B){var a=g.e$(G.segments,B);
a>=0||a<0&&(-a-1)%2===1||(a=-a-1,a>0&&B-G.segments[a-1]===1&&a<G.segments.length&&G.segments[a]-B===1?(g.ia(G.segments,a),g.ia(G.segments,a-1)):a>0&&B-G.segments[a-1]===1?G.segments[a-1]=B:a<G.segments.length&&G.segments[a]-B===1?G.segments[a]=B:(g.xV(G.segments,a,0,B),g.xV(G.segments,a+1,0,B)))},XMJ=function(G,B,a,V,x,h){g.r.call(this);
this.policy=G;this.player=B;this.zH=a;this.V=V;this.B=x;this.Y=h;this.G=new K3;this.L=-1;this.C=this.X=this.j=null;this.XJ=0;this.W=new g.J8(this.ew,1E3,this);this.events=new g.Zh(this);g.X(this,this.W);g.X(this,this.events);this.events.K(B,"SEEK_COMPLETE",this.gU);this.gU();this.ew()},quk=function(G){return G.j&&G.j.K3?G.j.K3+G.player.F3()<G.player.getCurrentTime():!1},u2W=function(G,B){if(G.policy.A6&&G.player.m7()){var a=g.uM(B,G.policy,{});
a.set("pot",G.player.m7());a=a.Ex()}else a=g.uM(B,G.policy,{}).Ex();var V={format:"RAW",withCredentials:!0};if(G.policy.LN){V.method="POST";var x=B.G;x&&Object.keys(x).length>0?V.postBody=g.Yy(x,g.Pp):V.postBody=(0,g.pL)([120,0])}G.B&&(V.responseType="arraybuffer");var h=++G.XJ,e=(0,g.yT)();G.C=g.fB(a,V,3,100).then(function(w){if(G.policy.WK&&h%100===1){var K=(0,g.yT)();G.player.FJ("caprsp",{rn:h,ms:K-e,kb:(w.xhr.responseText.length/1024).toFixed()})}a:{w=w.xhr;G.TH();if(G.X){var l=!(G.B?w.response:
w.responseText)||w.status>=400;if(K=g.$ZX(w)){w=g.uM(G.X,G.policy,{});G.X.Ey(w,K);u2W(G,G.X);break a}l?G.player.FJ("capfail",{status:w.status}):(G.player.PG().S6("fcb_r"),K=G.X.nN[0].AX,G.V!=null&&G.L!==K&&(l=G.X.nN[0],G.B?G.V(w.response,(l.startTime+G.player.F3())*1E3):G.V(w.responseText,(l.startTime+G.player.F3())*1E3),G.L=K))}G.X=null;G.C=null}}).yC(function(w){G.X=null;
G.C=null;var K;G.player.FJ("capfail",{rn:h,status:(K=w.xhr)==null?void 0:K.status})});
G.X=B;$6h(G.G,G.X.nN[0].AX)},lt=function(G,B){g.Up.call(this,B);
this.j=G;this.T=B;this.C=null;this.L=!1;this.logger=new g.xY("caps");this.W=g.jQ(this.T.U())&&!this.j.isManifestless},L3a=function(G,B){var a=[],V;
for(V in G.j.j)if(G.j.j.hasOwnProperty(V)){var x=G.j.j[V];if(g.Ep(x,B||null)){var h=x.info.id,e=h,w="."+h,K="",l="";if(x=x.info.captionTrack)h=x.languageCode,e=x.displayName,w=x.vssId,K=x.kind,l=x.id;else{x=h;var k=g.ckk.get(x);k==null&&(k=Ql3[x]||Ql3[x.replace(/-/g,"_")],g.ckk.set(x,k));x=k;e=x||e}a.push(new g.Nk({id:V,languageCode:h,languageName:e,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:w,kind:K,captionId:l}))}}return a},TUf=function(G,B){return B!=null&&B in G.j.j?G.j.j[B]:null},
slC=function(G,B,a){var V=[],x;
for(x in G.j.j)if(G.j.j.hasOwnProperty(x)){var h=G.j.j[x];if(g.Ep(h,a||null)){var e=h.info.captionTrack;e&&e.languageCode===B&&V.push(h)}}return V.length?V[0]:null},kq=function(G,B,a,V,x,h,e,w,K,l){var k=l.isInline()&&!0,N={};
Object.assign(N,B);Object.assign(N,G.params);Object.assign(N,a);var d={};Object.assign(d,B.HD);G.params.HD&&Object.assign(d,G.params.HD);Object.assign(d,a.HD);k&&(N.windowOpacity=.6,d.backgroundOpacity=0);N.HD=d;var C=N.eK===1,z=[{Z:"span",J:"captions-text",N:{style:"word-wrap: normal; display: block;"}}],p,O,b;(w=w.Or("caption_edit_on_hover")&&((p=l.getVideoData().getPlayerResponse())==null?void 0:(O=p.captions)==null?void 0:(b=O.playerCaptionsTracklistRenderer)==null?void 0:b.openTranscriptCommand))&&
z.unshift({Z:"button",J:"caption-edit",N:{tabindex:"0","aria-label":Zoh()},D:[{Z:"svg",N:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},D:[{Z:"path",N:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.T.call(this,{Z:"div",J:"caption-window",N:{id:"caption-window-"+G.id,dir:C?"rtl":"ltr",tabindex:"0",lang:N.lang},D:z});var c=
this;this.W=[];this.Zx=!1;this.X=G;this.Qb=this.LN=null;this.playerWidth=h;this.playerHeight=e;this.V=null;this.maxWidth=h*.96;this.maxHeight=e*.96;this.j=N;this.m3=a;this.XJ=B;this.G=this.d1("captions-text");this.Md=this.G.style.getPropertyValue("box-decoration-break")!==""||this.G.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.qB=F3$(V,x,h,e);this.YD=K;w&&(this.L=this.d1("caption-edit"),this.K(this.L,"click",function(){c.YD()}));
this.type=0;this.Ur=this.qB*J$f(d);this.Yf=k;G=new g.T8(this.element,!0);g.X(this,G);G.subscribe("dragstart",this.Gr,this);G.subscribe("dragmove",this.dw,this);G.subscribe("dragend",this.Rk,this);this.Vb=this.MB=this.Dx=this.eJ=0;G="";this.j.windowOpacity&&(G=R49(this.j.windowColor),G="rgba("+G[0]+","+G[1]+","+G[2]+","+this.j.windowOpacity+")");B={"background-color":G,display:this.j.isVisible===!1?"none":"","text-align":A$9[this.j.textAlign]};this.Md&&(B["border-radius"]=G?this.Ur/8+"px":"");(this.C=
this.X.params.eK===2||this.X.params.eK===3)&&Yuh(this,this.element);g.K4(this.element,B);if(k){var H;(H=this.element.parentElement)==null||H.style.setProperty("--caption-window-color",G)}switch(this.j.T4){case 0:case 1:case 2:g.hi(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.hi(this.element,"ytp-caption-window-bottom")}},Yuh=function(G,B){var a="vertical-rl";
G.j.Qn===1&&(a="vertical-lr");g.di&&(a=a==="vertical-lr"?"tb-lr":"tb-rl");g.K4(B,"-o-writing-mode",a);g.K4(B,"-webkit-writing-mode",a);g.K4(B,"writing-mode",a);g.K4(B,"text-orientation","upright");g.hi(B,"ytp-vertical-caption");G.X.params.eK===3&&(g.K4(B,"text-orientation",""),g.K4(B,"transform","rotate(180deg)"))},J$f=function(G){var B=1+.25*(G.fontSizeIncrement||0);
if(G.offset===0||G.offset===2)B*=.8;return B},ioC=function(G,B){var a={},V=B.background?B.background:G.j.HD.background;
if(B.backgroundOpacity!=null||B.background){var x=B.backgroundOpacity!=null?B.backgroundOpacity:G.j.HD.backgroundOpacity;V=R49(V);a.background="rgba("+V[0]+","+V[1]+","+V[2]+","+x+")";G.Md&&(a["box-decoration-break"]="clone",a["border-radius"]=G.Ur/8+"px")}if(B.fontSizeIncrement!=null||B.offset!=null)a["font-size"]=G.qB*J$f(B)+"px";V=1;x=B.color||G.j.HD.color;if(B.color||B.textOpacity!=null)x=R49(x),V=B.textOpacity==null?G.j.HD.textOpacity:B.textOpacity,x="rgba("+x[0]+","+x[1]+","+x[2]+","+V+")",
a.color=x,a.fill=x;var h=B.charEdgeStyle;h===0&&(h=void 0);if(h){x="rgba(34, 34, 34, "+V+")";var e="rgba(204, 204, 204, "+V+")";B.f0&&(e=x=B.f0);var w=G.qB/16/2,K=Math.max(w,1),l=Math.max(2*w,1),k=Math.max(3*w,1),N=Math.max(5*w,1);V=[];switch(h){case 4:for(;k<=N;k+=w)V.push(l+"px "+l+"px "+k+"px "+x);break;case 1:l=window.devicePixelRatio>=2?.5:1;for(h=K;h<=k;h+=l)V.push(h+"px "+h+"px "+x);break;case 2:V.push(K+"px "+K+"px "+e);V.push("-"+K+"px -"+K+"px "+x);break;case 3:for(k=0;k<5;k++)V.push("0 0 "+
l+"px "+x)}a["text-shadow"]=V.join(", ")}x="";switch(B.fontFamily){case 1:x='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:x='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:x='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:x='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:x='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:x=g.T9()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:x='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}x&&(a["font-family"]=x);x=B.offset;x==null&&(x=G.j.HD.offset);switch(x){case 0:a["vertical-align"]="sub";break;case 2:a["vertical-align"]="super"}B.fontFamily===7&&(a["font-variant"]="small-caps");B.bold&&(a["font-weight"]="bold");B.italic&&(a["font-style"]="italic");B.underline&&(a["text-decoration"]=
"underline");B.N1H&&(a.visibility="hidden");B.FL===1&&G.C&&(a["text-combine-upright"]="all",a["text-orientation"]="mixed",x=g.o$||g.It,G.X.params.eK===3?a.transform=x?"rotate(90deg)":"rotate(180deg)":x&&(a.transform="rotate(-90deg)"));if(B.tN===1||B.tN===2||B.tN===3||B.tN===4||B.tN===5)if(g.o$)a["font-weight"]="bold";else switch(a["text-emphasis-style"]="filled circle",a["text-emphasis-color"]="currentcolor",a["webkit-text-emphasis"]="filled circle",B.tN){case 4:case 3:a["text-emphasis-position"]=
"under left";a["webkit-text-emphasis-position"]="under left";break;case 5:case 2:a["text-emphasis-position"]="over right",a["webkit-text-emphasis-position"]="over right"}return a},NB=function(G){G=G.split("px");
return G.length>0?(G=Number(G[0]))?G:0:0},PQl=function(G){G.V=g.M6("SPAN");
g.K4(G.V,{display:"block"});g.hi(G.V,"caption-visual-line");G.G.appendChild(G.V)},oj3=function(G,B){var a=g.M6("SPAN");
g.K4(a,{display:"inline-block","white-space":"pre-wrap"});g.K4(a,ioC(G,B));a.classList.add("ytp-caption-segment");G.V.appendChild(a);a.previousElementSibling&&(g.K4(a.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.K4(a,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return a},MHW=function(G,B,a){G.Zx=G.Zx||!!a;
var V={};Object.assign(V,G.j.HD);Object.assign(V,a||B.j);Object.assign(V,G.m3.HD);(a=!G.V)&&PQl(G);for(var x=G.LN&&G.Qb&&g.no(V,G.Qb)?G.LN:oj3(G,V),h=typeof B.text==="string",e=h?B.text.split("\n"):[B.text],w=0;w<e.length;w++){var K=w>0||!B.append,l=e[w];K&&!a?(PQl(G),x=oj3(G,V)):K&&a&&(a=!1);l&&(x.appendChild(h?g.GT(l):l),h||l.tagName!=="RUBY"||l.childElementCount!==4||g.o$||!g.NV(l.children[2],"text-emphasis")||(K=G.C?"padding-right":"padding-top",g.NV(l.children[2],"text-emphasis-position")&&(K=
G.C?"padding-left":"padding-bottom"),g.Yj?g.K4(x,K,"1em"):g.K4(x,K,"0.5em")))}G.Qb=V;G.LN=x;G.W.push(B)},F3$=function(G,B,a,V){var x=B/360*16;
B>=G&&(G=640,V>a*1.3&&(G=480),x=a/G*16);return x},BQ3=function(){this.C=this.time=this.mode=this.X=0;
this.G=new GT7(this);this.B=new GT7(this);this.j=[];this.clear()},Vs2=function(G,B,a){if(G===255&&B===255||!G&&!B)return{l4:G,
Ir:B,result:0};G=aaa[G];B=aaa[B];if(G&128){var V;if(V=!(B&128))V=B,V=a.I4()&&a.Ir===V;if(V)return{l4:G,Ir:B,result:1}}else if(B&128&&1<=G&&G<=31)return{l4:G,Ir:B,result:2};return{l4:G,Ir:B,result:3}},h27=function(G,B,a,V){B===255&&a===255||!B&&!a?(++G.C===45&&G.reset(),G.G.X.clear(),G.B.X.clear()):(G.C=0,x_2(G.G,B,a,V))},e2a=function(G,B){G.j.sort(function(x,h){var e=x.time-h.time;
return e===0?x.order-h.order:e});
for(var a=g.m(G.j),V=a.next();!V.done;V=a.next())V=V.value,G.time=V.time,V.type===0?h27(G,V.Iv,V.UP,B):V.type===1&&G.X&496&&x_2(G.B,V.Iv,V.UP,B);G.j.length=0},dh=function(){this.type=0},C3=function(){this.state=this.Ir=this.l4=0},WE9=function(){this.timestamp=this.j=0},zt=function(G){this.B=G;
this.C=[];this.j=this.X=this.row=0;this.style=new dh;for(G=this.G=0;G<=15;G++){this.C[G]=[];for(var B=0;B<=32;B++)this.C[G][B]=new WE9}},tH=function(G,B){if(G.style.type===3){for(var a=0,V=0,x=G.B.time+0,h="",e="",w=x,K=1;K<=15;++K){for(var l=!1,k=V?V:1;k<=32;++k){var N=G.C[K][k];
if(N.j!==0){a===0&&(a=K,V=k);l=String.fromCharCode(N.j);var d=N.timestamp;d<x&&(x=d);N.timestamp=w;e&&(h+=e,e="");h+=l;l=!0}if((N.j===0||k===32)&&l){e="\n";break}else if(V&&!l)break}if(a&&!l)break}h&&B.G(a,V,x,w,h)}else for(V=a=0,h=x=G.B.time+0,e=1;e<=15;++e)for(w="",K=1;K<=32;++K)if(k=G.C[e][K],N=k.j,N!==0&&(a===0&&(a=e,V=K),l=String.fromCharCode(N),d=k.timestamp,d<=x&&(x=d),w+=l,k.reset()),K===32||N===0)w&&B.G(a,V,x,h,w),x=h,w="",V=a=0},NQJ=function(G,B){switch(G){case 0:return wiC[(B&127)-32];
case 1:return KEh[B&15];case 2:return la7[B&31];case 3:return kT$[B&31]}return 0},mm=function(G){return G.C[G.row][G.X]},IT=function(G,B,a){B>=2&&G.X>1&&(--G.X,mm(G).j=0);
var V=mm(G);V.timestamp=G.B.time+0;V.j=NQJ(B,a);G.X<32&&G.X++},d_C=function(G,B,a,V){for(var x=0;x<V;x++)for(var h=0;h<=32;h++){var e=G.C[B+x][h],w=G.C[a+x][h];
e.j=w.j;e.timestamp=w.timestamp}},gh=function(G,B,a){for(var V=0;V<a;V++)for(var x=0;x<=32;x++)G.C[B+V][x].reset()},Cf8=function(G){G.row=G.j>0?G.j:1;
G.X=1;gh(G,0,15)},z2C=function(G){this.C=G;
this.B=0;this.style=new dh;this.L=new zt(this.C);this.W=new zt(this.C);this.text=new zt(this.C);this.X=this.L;this.G=this.W;this.j=this.X},tsC=function(G,B,a){var V=G.X,x=!1;
switch(G.style.get()){case 4:case 1:case 2:G.style.get()===4&&V.j>0||(tH(V,a),Cf8(G.X),Cf8(G.G),V.row=15,V.j=B,x=!0)}G.style.set(3);G.j=V;G.j.style=G.style;G.C.mode=1<<V.G;x?V.X=1:V.j!==B&&(V.j>B?(tH(V,a),gh(V,V.row-V.j,B)):V.row<B&&(B=V.j),V.j=B)},m_J=function(G){G.style.set(1);
G.j=G.G;G.j.j=0;G.j.style=G.style;G.C.mode=1<<G.j.G},IaC=function(G){G.style.set(4);
G.j=G.text;G.j.style=G.style;G.C.mode=1<<G.j.G},GT7=function(G){this.j=G;
this.B=0;this.C=new z2C(this.j);this.L=new z2C(this.j);this.X=new C3;this.G=this.C},x_2=function(G,B,a,V){G.X.update();
B=Vs2(B,a,G.X);switch(B.result){case 0:return;case 1:case 2:return}var x=B.l4;a=B.Ir;if(32<=x||!x)G.j.mode&G.j.X&&(B=x,B&128&&(B=127),a&128&&(a=127),G=G.G.j,B&96&&IT(G,0,B),a&96&&IT(G,0,a),B!==0&&a!==0&&G.style.type===3&&tH(G,V));else if(x&16)a:if(!G.X.matches(x,a)&&(B=G.X,B.l4=x,B.Ir=a,B.state=2,B=x&8?G.L:G.C,G.G=B,G.j.mode=1<<(G.B<<2)+(B.B<<1)+(B.style.type===4?1:0),(G.j.mode|1<<(G.B<<2)+(B.B<<1)+(B.style.type!==4?1:0))&G.j.X))if(a&64){V=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(x&7)<<1|a>>5&1];
G=a&16?((a&14)>>1)*4:0;a=B.j;switch(B.style.get()){case 4:V=a.row;break;case 3:if(V!==a.row){if(V<a.j&&(V=a.j,V===a.row))break;var h=1+a.row-a.j,e=1+V-a.j;d_C(a,e,h,a.j);B=h;x=a.j;e<h?(h=e+x-h,h>0&&(B+=h,x-=h)):(h=h+x-e,h>0&&(x-=h));gh(a,B,x)}}a.row=V;a.X=G+1}else switch(x&7){case 1:switch(a&112){case 32:IT(B.j,0,32);break a;case 48:a===57?(V=B.j,mm(V).j=0,V.X<32&&V.X++):IT(B.j,1,a&15)}break;case 2:a&32&&IT(B.j,2,a&31);break;case 3:a&32&&IT(B.j,3,a&31);break;case 4:case 5:if(32<=a&&a<=47)switch(a){case 32:m_J(B);
break;case 33:V=B.j;V.X>1&&(--V.X,mm(V).j=0);break;case 36:V=B.j;B=mm(V);for(G=0;G<=15;G++)for(a=0;a<=32;a++)if(V.C[G][a]===B){for(;a<=32;a++)V.C[G][a].reset();break}break;case 37:tsC(B,2,V);break;case 38:tsC(B,3,V);break;case 39:tsC(B,4,V);break;case 40:IT(B.j,0,32);break;case 41:B.style.set(2);B.j=B.X;B.j.j=0;B.j.style=B.style;B.C.mode=1<<B.j.G;break;case 42:V=B.text;V.j=15;V.style.set(4);Cf8(V);IaC(B);break;case 43:IaC(B);break;case 44:G=B.X;switch(B.style.get()){case 1:case 2:case 3:tH(G,V)}gh(G,
0,15);break;case 45:b:{G=B.j;switch(B.style.get()){default:case 2:case 1:break b;case 4:if(G.row<15){++G.row;G.X=1;break b}break;case 3:}G.j<2&&(G.j=2,G.row<G.j&&(G.row=G.j));B=G.row-G.j+1;tH(G,V);d_C(G,B,B+1,G.j-1);gh(G,G.row,1)}break;case 46:gh(B.G,0,15);break;case 47:tH(B.X,V),B.G.updateTime(B.C.time+0),V=B.G,B.G=B.X,B.X=V,m_J(B)}break;case 7:switch(a){case 33:case 34:case 35:V=B.j,(V.X+=a&3)>32&&(V.X=32)}}},goh=function(){},p3=function(G,B,a,V,x,h,e){h=h===void 0?!1:h;
e=e===void 0?null:e;g.V1.call(this,G,G+B,{priority:a,namespace:"captions"});this.windowId=V;this.text=x;this.append=h;this.j=e},U_a=function(G,B,a,V,x,h,e){var w=h[0],K=e[w.getAttribute("p")];
if(K.Bx===1){var l=h[1],k=h[2];h=h[3];w.getAttribute("t");l.getAttribute("t");k.getAttribute("t");h.getAttribute("t");w.getAttribute("p");l.getAttribute("p");h.getAttribute("p");e=e[k.getAttribute("p")];w=piW(w.textContent,l.textContent,k.textContent,h.textContent,e);return new p3(G,B,x,a,w,V,K)}switch(K.Bx){case 9:case 10:K.tN=1;break;case 11:K.tN=2;break;case 12:K.tN=3;break;case 13:K.tN=4;break;case 14:K.tN=5}return new p3(G,B,x,a,w.textContent||"",V,K)},piW=function(G,B,a,V,x){var h=g.T9(),e=
h?g.M6("DIV"):g.M6("RUBY"),w=g.M6("SPAN");
w.textContent=G;e.appendChild(w);G=h?g.M6("DIV"):g.M6("RP");G.textContent=B;e.appendChild(G);B=h?g.M6("DIV"):g.M6("RT");B.textContent=a;e.appendChild(B);a=x.Bx;if(a===10||a===11||a===12||a===13||a===14)if(g.K4(B,"text-emphasis-style","filled circle"),g.K4(B,"text-emphasis-color","currentcolor"),g.K4(B,"webkit-text-emphasis","filled circle"),x.Bx===11||x.Bx===13)g.K4(B,"webkit-text-emphasis-position","under left"),g.K4(B,"text-emphasis-position","under left");a=!0;if(x.Bx===4||x.Bx===7||x.Bx===12||
x.Bx===14)g.K4(e,"ruby-position","over"),g.K4(e,"-webkit-ruby-position","before");else if(x.Bx===5||x.Bx===6||x.Bx===11||x.Bx===13)g.K4(e,"ruby-position","under"),g.K4(e,"-webkit-ruby-position","after"),a=!1;x=h?g.M6("DIV"):g.M6("RP");x.textContent=V;e.appendChild(x);h&&(V=a,g.K4(e,{display:"inline-block",position:"relative"}),h=e.firstElementChild.nextElementSibling,g.K4(h,"display","none"),h=h.nextElementSibling,g.K4(h,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.K4(e.lastElementChild,"display","none"),V?(g.K4(e,"padding-top","0.6em"),g.K4(h,"top","0")):(g.K4(e,"padding-bottom","0.6em"),g.K4(h,"bottom","0")));return e},UR=function(){g.r.apply(this,arguments)},OR=function(G,B,a,V,x){g.V1.call(this,G,G+B,{priority:a,
namespace:"captions"});this.id=V;this.params=x;this.j=[]},Oas=function(G){var B="_"+ER++;
return new OR(0,0x8000000000000,0,B,G)},jC=function(G){UR.call(this);
this.C=G;this.pens={};this.W={};this.V={};this.G="_"+ER++;this.L={};this.X=this.j=null;this.B=!0},bt=function(G,B){G=G.getAttribute(B);
if(G!=null)return Number(G)},yv=function(G,B){G=G.getAttribute(B);
if(G!=null)return G==="1"},ce=function(G,B){G=bt(G,B);
return G!==void 0?G:null},f3=function(G,B){G=G.getAttribute(B);
if(G!=null)return n3.test(G),G},Eo9=function(G,B){var a={},V=B.getAttribute("ws");
Object.assign(a,V?G.V[V]:G.C);G=ce(B,"mh");G!=null&&(a.xb=G);G=ce(B,"ju");G!=null&&(a.textAlign=G);G=ce(B,"pd");G!=null&&(a.eK=G);G=ce(B,"sd");G!=null&&(a.Qn=G);G=f3(B,"wfc");G!=null&&(a.windowColor=G);B=bt(B,"wfo");B!==void 0&&(a.windowOpacity=B/255);return a},jLk=function(G,B){var a={},V=B.getAttribute("wp");
V&&Object.assign(a,G.W[V]);G=ce(B,"ap");G!=null&&(a.T4=G);G=bt(B,"cc");G!=null&&(a.pL=G);G=bt(B,"ah");G!=null&&(a.Uy=G);G=bt(B,"rc");G!=null&&(a.Xa=G);B=bt(B,"av");B!=null&&(a.EC=B);return a},ba7=function(G,B,a,V){var x={};
Object.assign(x,jLk(G,B));Object.assign(x,Eo9(G,B));V?g.no(x,G.C)?(V=G.G,x=G.C):V="_"+ER++:V=B.getAttribute("id")||"_"+ER++;G=bt(B,"t")+a;B=bt(B,"d")||0x8000000000000;if(x.eK===2||x.eK===3)a=x.Xa,x.Xa=x.pL,x.pL=a;return new OR(G,B,0,V,x)},He=function(G){UR.call(this);
this.B=G;this.j=new Map;this.C=new Map;this.G=new Map;this.X=new Map},ve=function(G){G=g.eH(Math.round(G),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-G.length)+G},yw7=function(G,B,a,V,x){V===0&&(V=0x8000000000000);
var h={};B.wpWinPosId&&Object.assign(h,G.C.get(B.wpWinPosId));B.wsWinStyleId&&Object.assign(h,G.G.get(B.wsWinStyleId));G=B.rcRowCount;G!==void 0&&(h.Xa=G);B=B.ccColCount;B!==void 0&&(h.pL=B);if(h.eK===2||h.eK===3)B=h.Xa,h.Xa=h.pL,h.pL=B;return new OR(a,V,0,x,h)},DL=function(G,B,a){g.Up.call(this,G);
this.videoData=B;this.audioTrack=a;this.B=B.Ab},SC=function(G,B,a,V,x,h,e,w,K,l){kq.call(this,G,B,a,V,x,h,e,w,K,l);
this.type=1},RT=function(G,B,a){this.trackData=G;
this.L=a;this.version=this.B=this.C=this.byteOffset=0;this.X=[];this.j=new DataView(this.trackData)},ZL=function(G){var B=G.byteOffset;
G.byteOffset+=1;return G.j.getUint8(B)},rh=function(G){var B=G.byteOffset;
G.byteOffset+=4;return G.j.getUint32(B)},$q=function(G,B){UR.call(this);
this.X=G;this.C=B;this.track=this.C.languageName==="CC3"?4:0;this.j=new BQ3;this.j.X=1<<this.track},nol=function(G){if(typeof G==="string")return!1;
G=new RT(G,8,0);return cwW(G)},cwW=function(G){if(!(G.byteOffset<G.j.byteLength)||rh(G)!==1380139777)return!1;
G.version=ZL(G);if(G.version>1)return!1;ZL(G);ZL(G);ZL(G);return!0},XH=function(G,B,a,V,x,h,e,w,K,l){kq.call(this,G,B,a,V,x,h,e,w,K,l);
var k=this;this.type=2;this.HS=[];this.zH=this.Y=this.SJ=0;this.GH=NaN;this.QW=0;this.wO=null;this.Er=new g.J8(this.NCN,433,this);this.L&&(l.createClientVe(this.L,this,167342),this.K(this.L,"click",function(){l.logClick(k.L)}),G=new g.T8(this.element,!0),g.X(this,G),G.subscribe("hoverstart",function(){l.logVisibility(k.L,!0)},this));
g.hi(this.element,"ytp-caption-window-rollup");g.X(this,this.Er);g.K4(this.element,"overflow","hidden")},faJ=function(G,B){if(!B)return"";
G.C&&G.X.params.Qn!==1&&(B*=-1);return"translate"+(G.C?"X":"Y")+"("+B+"px)"},Haa=function(G){G.HS=Array.from(G.element.getElementsByClassName("caption-visual-line"));
for(var B=G.X.params.Xa,a=0,V=0,x=G.HS.length-1;a<B&&x>-1;){var h=G.HS[x];V+=G.C?h.offsetWidth:h.offsetHeight;a++;x--}G.Y=V;B=Math;a=B.max;isNaN(G.GH)&&((V=G.j.pL)?(x=g.M6("SPAN"),g.es(x,"\u2013".repeat(V)),g.K4(x,ioC(G,G.j.HD)),G.G.appendChild(x),G.GH=x.offsetWidth,G.G.removeChild(x)):G.GH=0);V=G.G;G.zH=a.call(B,G.GH,G.QW,(G.C?V.offsetHeight:V.offsetWidth)+1)},vok=function(G,B){Haa(G);
var a=G.HS.reduce(function(h,e){return(G.C?e.offsetWidth:e.offsetHeight)+h},0);
a=G.Y-a;if(a!==G.SJ){var V=a>0&&G.SJ===0,x=a<G.SJ;B||isNaN(a)||V||!x||(g.hi(G.element,"ytp-rollup-mode"),g.iC(G.Er));g.K4(G.G,"transform",faJ(G,a));G.SJ=a}Haa(G)},D_3=function(G,B,a,V){var x=this;
this.T=G;this.X=B;this.logger=a;this.SE=V;this.Pf=[];this.YJ=[];this.zW=null;this.vC={ctS:function(){return x.zW},
yk:function(){return x.Pf}};
G=g.kf(this.T.U().experiments,"html5_override_micro_discontinuities_threshold_ms");this.j=G>0?G:10},Zal=function(G,B){G.zW=function(a,V){if(a.info.G){var x=a;
if(G.YJ.length>0){for(x=G.YJ.shift();G.YJ.length>0;)x=g.o7(x,G.YJ.shift());x=g.o7(x,a)}if(x){a=x;try{var h=g.MC(a)*1E3}catch(l){h=a.info.startTime*1E3}try{var e=g.cjx(a)*1E3}catch(l){e=a.info.duration*1E3}if(h<0||e<0)h<0&&(h=a.info.startTime*1E3),e<0&&(e=a.info.duration*1E3);a.info.startTime=h/1E3;a.info.Sn=h/1E3;a.info.duration=e/1E3;a.info.L=e/1E3;h=G.mq(x);e=h.AX;h={formatId:h.formatId,startTimeMs:h.startTimeMs,durationMs:h.durationMs,XO:e,Xh:e};e=SzC(G.Pf,h.startTimeMs);var w=(a=e>=0?G.Pf[e]:
null)?a.startTimeMs+a.durationMs:0,K=h.startTimeMs+h.durationMs;!a||h.startTimeMs-w>G.j?G.Pf.splice(e+1,0,h):(a.durationMs=Math.max(w,K)-a.startTimeMs,a.Xh=Math.max(a.Xh,h.Xh));V(G.Pf);V=x.k_();R23(G.X,V.buffer.slice(V.byteOffset,V.byteLength+V.byteOffset),B,x.info.Sn)}else G.logger.j(350058965,"Empty slice")}else G.YJ.push(a)};
G.T.addEventListener("sabrCaptionsDataLoaded",G.zW)},SzC=function(G,B){G=g.e$(G,{startTimeMs:B},function(a,V){return a.startTimeMs-V.startTimeMs});
return G>=0?G:-G-2},rw2=function(G,B){g.Up.call(this,B);
this.j=G;this.T=B;this.logger=new g.xY("caps");this.C=this.L=null;this.W=new D_3(this.T,this,this.logger,this.j.SE)},R23=function(G,B,a,V){G.logger.debug(function(){return"SABR captions data received for "+V});
G.L?G.C==null?G.logger.j(350058965,"Null loaded track meta data at captions data received"):a.yR(B,G.C,V*1E3):G.logger.j(350058965,"Null Representation at captions data received")},$_C=function(G,B){var a=[],V;
for(V in G.j.j)if(G.j.j.hasOwnProperty(V)){var x=G.j.j[V];if(g.Ep(x,B||null)){var h=x.info.id,e=h,w="."+h,K="",l="";if(x=x.info.captionTrack)h=x.languageCode,e=x.displayName,w=x.vssId,K=x.kind,l=x.id;a.push(new g.Nk({id:V,languageCode:h,languageName:e,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:w,kind:K,captionId:l}))}}return a},XiJ=function(G,B,a){var V=[],x;
for(x in G.j.j)if(G.j.j.hasOwnProperty(x)){var h=G.j.j[x];if(g.Ep(h,a||null)){var e=h.info.captionTrack;e&&e.languageCode===B&&V.push(h)}}return V.length?V[0]:null},qzh=function(G,B){if(!g.mc_(G)||G.j!=null&&g.jQ(B.U())&&!G.j.isManifestless&&G.j.j.rawcc!=null)return!1;
B=!!G.j&&G.j.isManifestless&&Object.values(G.j.j).some(function(a){return g.Ep(a,"386")});
G=!!G.j&&!G.j.isManifestless&&g.Qrc(G.j);return B||G},qB=function(){UR.call(this)},ums=function(G,B,a,V,x,h,e,w,K){switch(e.tagName){case "b":w.bold=!0;
break;case "i":w.italic=!0;break;case "u":w.underline=!0}for(var l=0;l<e.childNodes.length;l++){var k=e.childNodes[l];if(k.nodeType===3)k=new p3(B,a,V,x.id,k.nodeValue,h||l>0,g.yw(w)?void 0:w),K.push(k),x.j.push(k);else{var N={};Object.assign(N,w);ums(G,B,a,V,x,!0,k,N,K)}}},QLJ=function(G){var B=G.split(":");
G=0;B=g.m(B);for(var a=B.next();!a.done;a=B.next())G=G*60+Number(a.value);return G*1E3},LEl=function(G,B,a,V){V=Object.assign({xb:0},V);
return new OR(G,B,a,"_"+ER++,V)},ut=function(G,B){g.r.call(this);
this.T=G;this.md=B;this.j=null;this.X=this.T.Nn();this.logger=new g.xY("caps")},sL$=function(G,B,a){if(typeof B==="string"||nol(B))return[{trackData:B,
GX:a}];var V=new DataView(B);if(V.byteLength<=8||V.getUint32(4)!==1718909296)return[];var x=g.Z1b(V);if(G.X&&x){var h=g.cXy(x),e=g.n2A(x);x=x.qL;h&&x&&G.X.pX(x,h,e)}G=g.MF(V,1835295092);if(!G||!G.length||!G[0].size)return[];h=[];for(e=0;e<G.length;e++)x=G[e],x=new Uint8Array(B,x.dataOffset,x.size-(x.dataOffset-x.offset)),x=g.yz(x),h.push({trackData:x,GX:a+e*1E3});TQC(V,h,a);return h=h.filter(function(w){return!!w.trackData})},TQC=function(G,B,a){var V=g.TO(G,0,1836476516),x=9E4;
V&&(x=g.si(V)||9E4);V=0;for(var h=g.MF(G,1836019558),e=0;e<h.length;e++){var w=h[e];e<B.length&&(w=g.TO(G,w.dataOffset,1953653094))&&(w=g.TO(G,w.dataOffset,1952867444))&&(w=g.PU(w)/x*1E3,e===0&&(V=w),B[e].GX=w-V+a||a*e*1E3)}},FEW=function(G){var B={};
if(G=g.zk(G))B.lang=G,g.Zsl.test(G)&&(B.eK=1);return B},Qv=function(G){g.go.call(this,G);
var B=this;this.T=G;this.LN=[];this.HS={};this.Er={};this.V=!1;this.G="NONE";this.j=this.Y=this.zH=this.qB=this.eJ=null;this.QW={gJ:function(){B.gJ()},
yR:function(h,e,w,K){B.yR(h,e,w,K)}};
this.X=null;this.md=this.T.U();this.videoData=this.T.getVideoData();this.Dx=this.T.g1();var a;this.Vb=(a=this.T.getVideoData(1))==null?void 0:g.AC(a);this.C={HD:{}};this.L={HD:{}};g.oS(this.videoData)?this.G="OFFLINE":qzh(this.videoData,this.T)?this.G="SABR_LIVE":g.RNK(this.videoData,this.T)?this.G="LIVE":this.videoData.captionTracks.length?this.G="INNERTUBE":this.videoData.xF&&(this.G="TTS");this.Ur=this.md.controlsType==="3";this.MB=new ut(this.T,this.md);this.GH=new g.Zh(this);this.W=new g.T({Z:"div",
J:"ytp-caption-window-container",N:{id:"ytp-caption-window-container"}});this.XJ={top:0,right:0,bottom:0,left:0,width:1,height:1};a=null;var V=g.ZA("yt-html5-player-modules::subtitlesModuleData");V&&(a=new g.y_(V));this.storage=a;var x;this.Yf=!((x=G.Zc())==null||!x.jH());this.B=Jw9(this);this.Zx=!this.B&&this.Ur&&this.Yf&&(this.G==="LIVE"||this.G==="SABR_LIVE");g.X(this,this.MB);this.B?this.SJ=this.Qb=null:(this.Qb=new g.F7(this.EO,void 0,this),g.X(this,this.Qb),this.SJ=new g.J8(this.EaN,2E3,this),
g.X(this,this.SJ));g.X(this,this.GH);g.SX(this.player,this.W.element,4);g.X(this,this.W);this.B||this.GH.K(G,"resize",this.xE);(this.fh=g.DB(this.md)&&!g.tt()&&!this.T.isFullscreen()&&!this.B&&!this.Zx)&&this.GH.K(G,"resize",this.yiN);this.GH.K(G,"onPlaybackAudioChange",this.Q0d);this.GH.K(G,g.hm("captions"),function(h){B.onCueRangeEnter(h)});
this.GH.K(G,g.ew("captions"),function(h){B.onCueRangeExit(h)});
this.Vb&&this.GH.K(G,"videodatachange",function(h,e){B.onVideoDataChange(h,e)});
Awf(this,r$a()||{});this.player.Ff("onCaptionsModuleAvailable")},PfC=function(G){if(G.md.Yf===1||G.videoData.Yj===1||g.ON(G.videoData,"yt:cc")==="alwayson")return!0;
if(G.videoData.captionTracks.length)var B=G.getAudioTrack().X;if(G.md.Yf===2){if(g.YF(G.md))var a=Yz9(G);else if(G.storage)try{a=G.storage.get("module-enabled")}catch(x){G.storage.remove("module-enabled")}else a=null;if(a!=null)return!!a}a=c$s(G.player.getAudioTrack(),g.YF(G.md));var V=g.ON(G.videoData,"yt:cc");if(ial(G)===void 0){if(a==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return V?V==="on":!0;if(a==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return V==="on"}else return V==="on";return B==="ON"||
g.ON(G.videoData,"yt:cc")==="on"},L3=function(G,B){if(G.X&&(B===void 0||!B)||!G.videoData.captionTracks.length)return!1;
G=G.getAudioTrack();return!!G.j||G.X==="FORCED_ON"},ial=function(G){var B=void 0,a=g.uP(g.qe(),65);
if(g.YF(G.md)&&a!=null){if(Yz9(G)!=null)return!1;B=!a}return B},sR=function(G,B){if(!G.j)return null;
if(G.Y&&G.Y.G)return G.Y.G;B=ooa(G,B);B=g.ha(G.j.X,B);var a=null;if(nj8(G.md)){var V=G.T.isInline()?void 0:g.SL("yt-player-caption-sticky-language");for(var x=[V,G.videoData.captionsLanguagePreference,G.md.captionsLanguagePreference,g.ON(G.videoData,"yt:cc_default_lang")],h=!1,e=0;e<x.length;e++){var w=x[e];if(w){h=!0;for(var K=0;K<B.length;K++)if(g.zk(B[K])===w)return B[K];for(K=0;K<B.length;K++)if(g.zk(B[K]).split("-")[0]===w.split("-")[0])return B[K]}}if(h&&G.j&&(x=G.j.B,x.length))for(x=g.m(x),
h=x.next();!h.done;h=x.next())if(h=h.value,h.languageCode===V){a=h;break}}else for(V=[G.videoData.captionsLanguagePreference,G.md.captionsLanguagePreference,g.ON(G.videoData,"yt:cc_default_lang")],x=0;x<V.length;x++)for(h=0;h<B.length;h++)if(g.zk(B[h])===V[x])return B[h];V=null;G.Y&&G.Y.C&&(V=G.Y.C);V||(V=B.find(function(l){return l.isDefault})||null);
V||(V=B[0]||Tt(G));V&&a&&g.zk(V).split("-")[0]!==a.languageCode.split("-")[0]&&(V=fQh(V,a));return V},Tt=function(G){return G.Y&&G.Y.j},FH=function(G){var B=Tt(G);
return!!B&&G.X===B},Ms2=function(G,B){var a=G.T.Zc().dO().textTracks;
G=G.X.toString();for(var V=0;V<a.length;V++){var x=a[V];x.id===G&&(B?x.mode!=="showing"&&(x.mode="showing"):x.mode==="showing"&&(x.mode="disabled"))}},Yq=function(G,B,a){G.loaded&&G.unload();
a!=null&&(G.V=a,G.V&&(g.YF(G.md)?JH(G,!!B):AH(G,!!B)));G.md.S("html5_report_caption_format_change")&&G5h(G,G.X,B,G.V,!1);G.X=B;L3(G)&&(B=Tt(G),G.md.S("html5_report_caption_format_change")&&G5h(G,G.X,B,G.V,!0),G.X=B);var V;Bps(G,(V=G.X)!=null?V:void 0);G.load()},VU7=function(G,B){if(B instanceof OR){var a=G.HS[B.id];
a&&a.X!==B&&(a.dispose(),delete G.HS[B.id],a=null);a||(a=a4k(G,B))&&(G.HS[B.id]=a)}else a=B.windowId,G.Er[a]||(G.Er[a]=[]),G.Er[a].push(B)},a4k=function(G,B){var a=xHC(G);
if(!a)return null;var V=G.X?g.zk(G.X):null;V&&g.Zsl.test(V)&&(B.params.eK=1);var x=G.Dx.getPlayerSize();V=x.height*G.XJ.height;x=x.width*G.XJ.width;G.md.playerStyle!=="google-live"||G.C.isDefault||Object.assign(B.params,G.C);switch(B.params.xb!=null?B.params.xb:B.j.length>1?1:0){case 1:return new SC(B,G.C,G.L,a.width,a.height,x,V,G.md.experiments,G.e3.bind(G),G.T);case 2:return new XH(B,G.C,G.L,a.width,a.height,x,V,G.md.experiments,G.e3.bind(G),G.T);default:return new kq(B,G.C,G.L,a.width,a.height,
x,V,G.md.experiments,G.e3.bind(G),G.T)}},Awf=function(G,B,a){a=a===void 0?!1:a;
var V=it.HD;G.C={};Object.assign(G.C,it);G.C.HD={};Object.assign(G.C.HD,V);G.L={HD:{}};var x=B.backgroundOverride?G.L:G.C,h=B.background||V.background;n3.test(h);x.HD.background=h;x=B.colorOverride?G.L:G.C;h=B.color||V.color;n3.test(h);x.HD.color=h;x=B.windowColorOverride?G.L:G.C;h=B.windowColor||it.windowColor;n3.test(h);x.windowColor=h;x=B.backgroundOpacityOverride?G.L:G.C;h=B.backgroundOpacity;h==null&&(h=V.backgroundOpacity);x.HD.backgroundOpacity=h;x=B.fontSizeIncrementOverride?G.L:G.C;h=B.fontSizeIncrement;
h==null&&(h=V.fontSizeIncrement);x.HD.fontSizeIncrement=h;h=B.fontStyleOverride?G.L:G.C;x=B.fontStyle;x==null&&(x=V.bold&&V.italic?3:V.bold?1:V.italic?2:0);h=h.HD;switch(x){case 1:h.bold=!0;delete h.italic;break;case 2:delete h.bold;h.italic=!0;break;case 3:h.bold=!0;h.italic=!0;break;default:delete h.bold,delete h.italic}x=B.textOpacityOverride?G.L:G.C;h=B.textOpacity;h==null&&(h=V.textOpacity);x.HD.textOpacity=h;x=B.windowOpacityOverride?G.L:G.C;h=B.windowOpacity;h==null&&(h=it.windowOpacity);x.windowOpacity=
h;x=B.charEdgeStyleOverride?G.L:G.C;h=B.charEdgeStyle;h==null&&(h=V.charEdgeStyle);x.HD.charEdgeStyle=h;x=B.fontFamilyOverride?G.L:G.C;h=B.fontFamily;h==null&&(h=V.fontFamily);x.HD.fontFamily=h;G.loaded&&G.xE();a&&g.D0("yt-player-caption-display-settings",B,2592E3)},h$7=function(G,B){if(!G.j)return{};
if(B){G.md.S("html5_report_caption_format_intent")&&!g.yw(B)&&G.jK(B.vss_id,"m");if(G.B||!g.Ag(B))return;if(g.yw(B)){Yq(G,null,!0);return}for(var a,V=g.ha(G.j.X,!0),x=0;x<V.length;x++){var h=V[x];h.languageCode!==B.languageCode||a&&(h.languageName!==B.languageName||(h.captionId||"")!==(B.captionId||"")||g.dt(h)!==B.displayName)||(a=B.translationLanguage?fQh(h,B.translationLanguage):h)}G.W7(B.position);!a||a===G.X&&G.loaded||(B=g.uD(),V=g.zk(a),B.length&&V===B[B.length-1]||(B.push(V),g.D0("yt-player-caption-language-preferences",
B)),nj8(G.md)&&!G.T.isInline()&&g.D0("yt-player-caption-sticky-language",V,2592E3),Yq(G,a,!0))}else return G.loaded&&G.X&&!FH(G)?g.C$(G.X):{};return""},WLl=function(G,B,a){B&&!G.zH?(B=Oas({eK:0,
lang:"en"}),G.zH=[B,new p3(B.start,B.end-B.start,0,B.id,a!=null?a:"Captions look like this")],G.player.z1(G.zH)):!B&&G.zH&&(e$a(G,G.zH),G.zH=null)},e$a=function(G,B){G.player.FO(B);
B=g.m(B);for(var a=B.next();!a.done;a=B.next())g.PW(G.LN,a.value);wh(G.Qb)},Bps=function(G,B){G.md.S("html5_modify_caption_vss_logging")&&(G.videoData.Bj=B)},xHC=function(G){var B=G.Dx.getVideoContentRect(!0).height,a=G.Dx.getVideoContentRect(!0).width;
if(!B||!a)return null;B*=G.XJ.height;a*=G.XJ.width;return{width:a,height:B}},AH=function(G,B){if(G.storage)try{G.storage.set("module-enabled",B)}catch(a){}},JH=function(G,B){G.T.isInline()||g.D0("yt-player-sticky-caption",B,2592E3)},Yz9=function(G){if(!G.T.isInline())return g.SL("yt-player-sticky-caption")},Jw9=function(G){var B,a=!((B=G.T.Zc())==null||!B.mJ());
return G.Ur&&a&&G.G!=="LIVE"&&G.G!=="SABR_LIVE"},ooa=function(G,B){g.rB(G.videoData)&&(B=!0);
B||(B=G.G==="TTS"?!1:G.G==="INNERTUBE"?!1:!0);return B||G.md.S("web_deprecate_always_includes_asr_setting")&&g.YF(G.md)?!0:!!g.uP(g.qe(),66)},G5h=function(G,B,a,V,x){x?G.GV(a,!0,"g"):V?B?G.GV(a,!!a,"m"):a&&G.GV(a,!0,"m"):!B&&a&&G.GV(a,!0,"s")};
g.Up.prototype.FR=g.Vb(77,function(){return!1});
g.Up.prototype.Jt=g.Vb(76,function(){});
g.Op.prototype.Jt=g.Vb(75,function(G,B,a){var V=this;this.TH();B=this.i9(G,B);var x=this.JX.U().S("html5_report_captions_ctmp_qoe"),h=(0,g.yT)();this.Kc();y$k(this,B,{format:"RAW",onSuccess:function(e){V.j=null;if(x){var w=(e.responseText.length/1024).toFixed(),K=(0,g.yT)();V.videoData.FJ("capresp",{ms:K-h,kb:w})}a.yR(e.responseText,G)},
onError:x?function(e){var w;e=(w=e==null?void 0:e.status)!=null?w:0;V.videoData.FJ("capfail",{status:e})}:void 0,
withCredentials:!0})});
g.jA.prototype.Jt=g.Vb(74,function(G,B,a){var V=this;this.TH();B=this.i9(G,B);this.Kc();this.j=g.bm(B,{format:"RAW",onSuccess:function(x){V.j=null;a.yR(x.responseText,G)},
withCredentials:!0})});
g.oi.prototype.F7=g.Vb(73,function(){for(var G=g.Lo(document,"track",void 0,this.j),B=0;B<G.length;B++)g.xo(G[B])});
g.Sy.prototype.F7=g.Vb(72,function(){this.mediaElement.F7()});
g.oi.prototype.jH=g.Vb(71,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.Sy.prototype.jH=g.Vb(70,function(){return this.mediaElement.jH()});
g.oi.prototype.mJ=g.Vb(69,function(){return!!this.j.textTracks});
g.Sy.prototype.mJ=g.Vb(68,function(){return this.mediaElement.mJ()});
g.oi.prototype.Oz=g.Vb(67,function(G){for(var B=0;B<G.length;B++)this.j.appendChild(G[B])});
g.Sy.prototype.Oz=g.Vb(66,function(G){this.mediaElement.Oz(G)});
g.Vn.prototype.pX=g.Vb(65,function(G,B,a){this.EZ.pX(G,B,a)});
g.sP.prototype.pX=g.Vb(64,function(G,B,a){this.X.set(G,{FF:B,Io:a})});
g.Fe.prototype.pX=g.Vb(63,function(G,B,a){this.Qb.pX(G,B,a)});
g.Vn.prototype.PZ=g.Vb(62,function(G){return this.EZ.PZ(G)});
g.Fe.prototype.PZ=g.Vb(61,function(G){var B=2;this.V.has(G)?B=0:g.krz(this,G)&&(B=1);return B});
g.bq.prototype.Eo=g.Vb(49,function(G){var B=this.app.It();return B?B.Eo(G):!1});
g.qd.prototype.Eo=g.Vb(48,function(G){return this.jJ.Zs.Eo(G)});
g.qP.prototype.Eo=g.Vb(47,function(G){return this.fM().some(function(B){return B.namespace===G})});
g.Xe.prototype.Eo=g.Vb(46,function(){return!1});
g.bq.prototype.jK=g.Vb(44,function(G,B){var a;(a=this.app.KN())==null||a.jK(G,B)});
g.qd.prototype.jK=g.Vb(43,function(G,B){this.jJ.jK(G,B)});
g.OL.prototype.jK=g.Vb(42,function(G,B){G=[G,B];g.UL(this,g.mR(this.provider),"cfi",G)});
g.rd.prototype.jK=g.Vb(41,function(G,B){this.qoe&&this.qoe.jK(G,B)});
g.KO.prototype.jK=g.Vb(40,function(G,B){this.Kh().jK(G,B)});
g.Xe.prototype.jK=g.Vb(39,function(){});
g.bq.prototype.GV=g.Vb(38,function(G,B,a){var V;(V=this.app.KN())==null||V.GV(G,B,a)});
g.qd.prototype.GV=g.Vb(37,function(G,B,a){this.jJ.GV(G,B,a)});
g.OL.prototype.GV=g.Vb(36,function(G,B,a){if(this.Qb!==G||this.m3!==B)B=B==="rawcc"?"":B,a=[G,B,this.Qb,a],g.UL(this,g.mR(this.provider),"cfs",a),this.Qb=G,this.m3=B});
g.rd.prototype.GV=g.Vb(35,function(G,B,a){this.qoe&&this.qoe.GV(G,B,a)});
g.KO.prototype.GV=g.Vb(34,function(G,B,a){this.Kh().GV(G,B,a)});
g.Xe.prototype.GV=g.Vb(33,function(){});
g.Mg.prototype.Hd=g.Vb(20,function(){return this.V});
g.mj.prototype.Hd=g.Vb(19,function(){var G;return((G=this.KN())==null?void 0:G.Nn())||null});
g.bq.prototype.Nn=g.Vb(18,function(){return this.app.Hd()});
g.qd.prototype.Nn=g.Vb(17,function(){return this.jJ.Nn()});
g.KO.prototype.Nn=g.Vb(16,function(){var G;return((G=this.CN)==null?void 0:G.Hd())||null});
g.Xe.prototype.Nn=g.Vb(15,function(){return null});
g.fT.prototype.Ob=g.Vb(1,function(G){return(G=this.OM(G))?G.j:0});
g.Ve.prototype.Ob=g.Vb(0,function(){return 0});
var Sua=/#(.)(.)(.)/,D6a=/^#(?:[0-9a-f]{3}){1,2}$/i,Ql3={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};K3.prototype.contains=function(G){G=g.e$(this.segments,G);return G>=0||G<0&&(-G-1)%2===1};
K3.prototype.length=function(){return this.segments.length/2};
g.t(XMJ,g.r);g.W=XMJ.prototype;g.W.yb=function(){g.r.prototype.yb.call(this);this.C&&this.C.cancel()};
g.W.gU=function(){this.seekTo(this.player.getCurrentTime())};
g.W.seekTo=function(G){G-=this.player.F3();var B=this.j;this.j=g.s3(this.zH.dK(G).nN);B!==this.j&&this.Y&&this.Y()};
g.W.reset=function(){this.G=new K3;this.L=-1;this.C&&(this.C.cancel(),this.C=null)};
g.W.ew=function(){this.TH();var G;if(G=this.j!=null)G=this.j,G=G.j.EY(G);if(G&&!this.C&&!(this.j&&this.j.startTime-this.player.getCurrentTime()>30)){G=this.j;G=G.j.PK(G);var B=G.nN[0],a;if((a=this.player.getVideoData())==null?0:a.enableServerStitchedDai)if(a=this.player.Nn()){var V=B.j.info.id,x=B.AX,h=G.nN[0].Sn;if(this.policy.LN){if(a=a.VP(h,x,V,3))G.G=a}else if(V=a.St(h,x,V,3))if(a=a.PZ(x),a===0)V&&(G.j=new g.pT(V));else if(a===2){this.W.start();quk(this)&&this.seekTo(this.player.getCurrentTime());
return}}B.j.index.Ie(B.AX)?(this.G.contains(G.nN[0].AX)||u2W(this,G),this.j=g.s3(G.nN)):quk(this)&&this.seekTo(this.player.getCurrentTime())}this.W.start()};
g.t(lt,g.Up);g.W=lt.prototype;g.W.Jt=function(G,B,a){var V=this;this.Kc();B=TUf(this,G.getId());B||(B=G.languageCode,B=this.j.isManifestless?slC(this,B,"386"):slC(this,B));if(B){var x=(B.index.Ob(B.index.Dh())-B.index.getStartTime(B.index.Dh()))*1E3,h=this.T.U(),e=new g.PB9(h),w=function(){V.C&&V.C.reset();V.L=!0};
h.S("html5_keep_caption_data_after_seek")&&(w=null);this.C=new XMJ(e,this.T,B,function(K,l){a.yR(K,G,l,x)},this.W||g.PX(B.info),w)}};
g.W.FR=function(){var G=this.L;this.L=!1;return G};
g.W.Fp=function(G){var B=this.T.U().S("html5_fallback_if_rawcc_missing");var a=this.j.j.rawcc!=null;if(!this.W||!a&&B)B=this.j.isManifestless?L3a(this,"386"):L3a(this);else{if(!a){this.logger.j(386248249,"rawcc used but unavailable");return}B=[new g.Nk({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Nk({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}B=g.m(B);
for(a=B.next();!a.done;a=B.next())g.pv(this.X,a.value);G.gJ()};
g.W.Kc=function(){this.C&&(this.C.dispose(),this.C=null)};
g.W.i9=function(){return""};
g.W.eX=function(){this.C&&(this.C.reset(),this.T.KD("captions"))};
var n3=/^#(?:[0-9a-f]{3}){1,2}$/i;var A$9=["left","right","center","justify"];g.t(kq,g.T);g.W=kq.prototype;g.W.Gr=function(G,B){this.MB=G;this.Vb=B;var a=g.gx(this.element,this.element.parentElement);this.eJ=G-a.x;this.Dx=B-a.y};
g.W.dw=function(G,B){if(G!==this.MB||B!==this.Vb){g.x$(this.element,"ytp-dragging")||g.hi(this.element,"ytp-dragging");var a=g.UK(this.element);G=G-this.eJ-.02*this.playerWidth;var V=B-this.Dx-.02*this.playerHeight,x=(G+a.width/2)/this.maxWidth*3;x=Math.floor(g.eH(x,0,2));var h=(V+a.height/2)/this.maxHeight*3;h=Math.floor(g.eH(h,0,2));B=x+h*3;G=(G+x/2*a.width)/this.maxWidth;G=g.eH(G,0,1)*100;a=(V+h/2*a.height)/this.maxHeight;a=g.eH(a,0,1)*100;this.X.params.T4=B;this.X.params.EC=a;this.X.params.Uy=
G;this.X.params.isDefault=!1;this.j.T4=B;this.j.EC=a;this.j.Uy=G;this.j.isDefault=!1;this.XJ.T4=B;this.XJ.EC=a;this.XJ.Uy=G;this.XJ.isDefault=!1;this.iO()}};
g.W.Rk=function(){g.WC(this.element,"ytp-dragging")};
g.W.iO=function(){this.wd(this.W)};
g.W.getType=function(){return this.type};
g.W.wd=function(G){var B=this.Yf?0:Math.min(this.FX(),this.maxWidth),a=this.jG(),V=this.Yf;if(V){var x=getComputedStyle(this.G.parentNode);x=NB(x.borderLeftWidth)+NB(x.borderRightWidth)+NB(x.paddingLeft)+NB(x.paddingRight)}else x=0;var h=x;x="";this.X.params.eK===3&&(x="rotate(180deg)");var e=V?"calc(96% - "+h+"px)":"96%";g.K4(this.element,{top:0,left:0,right:"",bottom:"",width:B?B+"px":"",height:a?a+"px":"","max-width":e,"max-height":e,margin:"",transform:""});this.g0(G);x={transform:x,top:"",left:"",
width:B?B+"px":"",height:a?a+"px":"","max-width":"","max-height":""};var w=this.j.Uy*.96+2;e=this.j.T4;switch(e){case 0:case 3:case 6:(V=this.j.HD.fontSizeIncrement)&&V>0&&this.j.eK!==2&&this.j.eK!==3&&(w=Math.max(w/(1+V*2),2));x.left=w+"%";break;case 1:case 4:case 7:x.left=w+"%";w=this.G.offsetWidth;B||w?(B=B||w+1,x.width=B+"px",x["margin-left"]=V?B/-2-h/2+"px":B/-2+"px"):x.transform+=" translateX(-50%)";break;case 2:case 5:case 8:x.right=100-w+"%"}V=this.j.EC*.96+2;switch(e){case 0:case 1:case 2:x.top=
V+"%";break;case 3:case 4:case 5:x.top=V+"%";(a=a||this.element.clientHeight)?(x.height=a+"px",x["margin-top"]=a/-2+"px"):x.transform+=" translateY(-50%)";break;case 6:case 7:case 8:x.bottom=100-V+"%"}g.K4(this.element,x);if(this.L){a=this.G.offsetHeight;V=1;for(B=0;B<G.length;B++)x=G[B],typeof x.text==="string"&&(V+=x.text.split("\n").length-1,x.append||B===0||V++);a/=V;this.L.style.height=a+"px";this.L.style.width=a+"px";this.element.style.paddingLeft=a+5+"px";this.element.style.paddingRight=a+
5+"px";G=Number(this.element.style.marginLeft.replace("px",""))-a-5;a=Number(this.element.style.marginRight.replace("px",""))-a-5;this.element.style.marginLeft=G+"px";this.element.style.marginRight=a+"px"}};
g.W.g0=function(G){var B;for(B=0;B<G.length&&G[B]===this.W[B];B++);if(this.Zx||this.W.length>B)B=0,this.Zx=!1,this.W=[],this.V=this.Qb=this.LN=null,g.aL(this.G);for(;B<G.length;B++)MHW(this,G[B])};
g.W.FX=function(){return 0};
g.W.jG=function(){return 0};
g.W.toString=function(){return g.T.prototype.toString.call(this)};BQ3.prototype.clear=function(){this.C=this.time=this.mode=0;this.j=[];this.reset()};
BQ3.prototype.reset=function(){this.mode=0;this.G.reset(0);this.B.reset(1)};
var aaa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];dh.prototype.set=function(G){this.type=G};
dh.prototype.get=function(){return this.type};
C3.prototype.clear=function(){this.state=0};
C3.prototype.update=function(){this.state=this.state===2?1:0};
C3.prototype.I4=function(){return this.state!==0};
C3.prototype.matches=function(G,B){return this.I4()&&G===this.l4&&B===this.Ir};
WE9.prototype.reset=function(){this.timestamp=this.j=0};
zt.prototype.updateTime=function(G){for(var B=1;B<=15;++B)for(var a=1;a<=32;++a)this.C[B][a].timestamp=G};
zt.prototype.debugString=function(){for(var G="\n",B=1;B<=15;++B){for(var a=1;a<=32;++a){var V=this.C[B][a];G=V.j===0?G+"_":G+String.fromCharCode(V.j)}G+="\n"}return G};
zt.prototype.reset=function(G){for(var B=0;B<=15;B++)for(var a=0;a<=32;a++)this.C[B][a].reset();this.G=G;this.j=0;this.X=this.row=1};
var wiC=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],KEh=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],la7=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],kT$=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];z2C.prototype.reset=function(G,B){this.B=B;this.style.set(2);this.X=this.L;this.G=this.W;this.j=this.X;var a=(G<<2)+(B<<1);this.L.reset(a);this.W.reset(a);this.text.reset((G<<2)+(B<<1)+1)};
GT7.prototype.reset=function(G){this.B=G;this.X.clear();this.G=this.C;this.C.reset(G,0);this.L.reset(G,1)};goh.prototype.G=function(){};g.t(p3,g.V1);p3.prototype.toString=function(){return g.V1.prototype.toString.call(this)};g.t(UR,g.r);UR.prototype.QN=function(){return[]};
UR.prototype.reset=function(){};g.t(OR,g.V1);OR.prototype.toString=function(){return g.V1.prototype.toString.call(this)};
var ER=0;g.t(jC,UR);jC.prototype.reset=function(){this.L={};this.X=this.j=null;this.B=!0};
jC.prototype.QN=function(G,B){G=G.firstChild;G.getAttribute("format");B=B||0;Number.isFinite(B);G=Array.from(G.childNodes);G=g.m(G);for(var a=G.next();!a.done;a=G.next())if(a=a.value,a.nodeType===1)switch(a.tagName){case "head":var V=a;break;case "body":var x=a}if(V)for(V=Array.from(V.childNodes),V=g.m(V),G=V.next();!G.done;G=V.next())if(G=G.value,G.nodeType===1)switch(G.tagName){case "pen":a=G.getAttribute("id");var h=this.pens,e={},w=G.getAttribute("p");w&&Object.assign(e,this.pens[w]);w=yv(G,"b");
w!=null&&(e.bold=w);w=yv(G,"i");w!=null&&(e.italic=w);w=yv(G,"u");w!=null&&(e.underline=w);w=ce(G,"et");w!=null&&(e.charEdgeStyle=w);w=ce(G,"of");w!=null&&(e.offset=w);w=f3(G,"bc");w!=null&&(e.background=w);w=f3(G,"ec");w!=null&&(e.f0=w);w=f3(G,"fc");w!=null&&(e.color=w);w=ce(G,"fs");w!=null&&w!==0&&(e.fontFamily=w);w=bt(G,"sz");w!==void 0&&(e.fontSizeIncrement=w/100-1);w=bt(G,"bo");w!==void 0&&(e.backgroundOpacity=w/255);w=bt(G,"fo");w!==void 0&&(e.textOpacity=w/255);w=ce(G,"rb");w!=null&&w!==10&&
w!==0&&(e.Bx=w>10?w-1:w);G=ce(G,"hg");G!=null&&(e.FL=G);h[a]=e;break;case "ws":a=G.getAttribute("id");this.V[a]=Eo9(this,G);break;case "wp":a=G.getAttribute("id"),this.W[a]=jLk(this,G)}if(x){V=[];x=Array.from(x.childNodes);x=g.m(x);for(G=x.next();!G.done;G=x.next())if(G=G.value,G.nodeType===1)switch(G.tagName){case "w":this.j=ba7(this,G,B,!1);(G=this.L[this.j.id])&&G.end>this.j.start&&(G.end=this.j.start);this.L[this.j.id]=this.j;V.push(this.j);break;case "p":var K=G;w=B;a=[];h=K.getAttribute("w")||
this.G;e=!!yv(K,"a");w=(bt(K,"t")||0)+w;var l=bt(K,"d")||5E3;e||(!this.B&&this.X&&this.X.windowId===h&&this.X.end>w&&(this.X.end=w),this.X&&this.X.text==="\n"&&(this.X.text=""));var k=e?6:5,N=K.getAttribute("p");N=N?this.pens[N]:null;var d=Array.from(K.childNodes);d.length&&(this.B=K.getAttribute("d")!=null);for(K=0;K<d.length;K++){var C=d[K],z=void 0;K>0&&(e=!0);var p=void 0;C.nodeType===1&&(p=C);if(p&&p.tagName==="s"){if((C=(C=p.getAttribute("p"))?this.pens[C]:null)&&C.Bx&&(C.Bx===1?(C=d.slice(K,
K+4),C.length===4&&(z=U_a(w,l,h,e,k,C,this.pens),K+=3)):z=U_a(w,l,h,e,k,[p],this.pens)),!z){var O=p;z=w;p=l;C=h;var b=e,c=k,H=O.textContent?O.textContent:"",R=O.getAttribute("p");R=R?this.pens[R]:null;O=bt(O,"t")||0;z=new p3(z+O,p-O,c,C,H,b,R)}}else z=new p3(w,l,k,h,C.textContent||"",e,N);a.push(z);this.X=z}if(a.length>0)for(a[0].windowId===this.G&&(this.j=ba7(this,G,B,!0),V.push(this.j)),G=g.m(a),a=G.next();!a.done;a=G.next())a=a.value,a.windowId=this.j.id,this.j.j.push(a),V.push(a)}B=V}else B=[];
return B};var wa7=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.t(He,UR);He.prototype.reset=function(){this.X.clear()};
He.prototype.QN=function(G,B){var a=JSON.parse(G);if(!a)return[];if(a.pens){G=0;for(var V=g.m(a.pens),x=V.next();!x.done;x=V.next()){x=x.value;var h={},e=x.pParentId;e&&Object.assign(h,this.j.get(e));x.bAttr&&(h.bold=!0);x.iAttr&&(h.italic=!0);x.uAttr&&(h.underline=!0);e=x.ofOffset;e!=null&&(h.offset=e);x.szPenSize!==void 0&&(h.fontSizeIncrement=x.szPenSize/100-1);e=x.etEdgeType;e!=null&&(h.charEdgeStyle=e);x.ecEdgeColor!==void 0&&(h.f0=ve(x.ecEdgeColor));e=x.fsFontStyle;e!=null&&e!==0&&(h.fontFamily=
e);x.fcForeColor!==void 0&&(h.color=ve(x.fcForeColor));x.foForeAlpha!==void 0&&(h.textOpacity=x.foForeAlpha/255);x.bcBackColor!==void 0&&(h.background=ve(x.bcBackColor));x.boBackAlpha!==void 0&&(h.backgroundOpacity=x.boBackAlpha/255);(e=x.rbRuby)&&e!==10&&(h.Bx=e>10?e-1:e,h.tN=wa7.get(h.Bx));x.hgHorizGroup&&(h.FL=x.hgHorizGroup);this.j.set(G++,h)}}if(a.wsWinStyles)for(G=0,V=g.m(a.wsWinStyles),x=V.next();!x.done;x=V.next())x=x.value,h={},(e=x.wsParentId)?Object.assign(h,this.G.get(e)):Object.assign(h,
this.B),x.mhModeHint!==void 0&&(h.xb=x.mhModeHint),x.juJustifCode!==void 0&&(h.textAlign=x.juJustifCode),x.pdPrintDir!==void 0&&(h.eK=x.pdPrintDir),x.sdScrollDir!==void 0&&(h.Qn=x.sdScrollDir),x.wfcWinFillColor!==void 0&&(h.windowColor=ve(x.wfcWinFillColor)),x.wfoWinFillAlpha!==void 0&&(h.windowOpacity=x.wfoWinFillAlpha/255),this.G.set(G++,h);if(a.wpWinPositions)for(G=0,V=g.m(a.wpWinPositions),x=V.next();!x.done;x=V.next())x=x.value,h={},(e=x.wpParentId)&&Object.assign(h,this.C.get(e)),x.ahHorPos!==
void 0&&(h.Uy=x.ahHorPos),x.apPoint!==void 0&&(h.T4=x.apPoint),x.avVerPos!==void 0&&(h.EC=x.avVerPos),x.ccCols!==void 0&&(h.pL=x.ccCols),x.rcRows!==void 0&&(h.Xa=x.rcRows),this.C.set(G++,h);if(a.events){G=[];a=g.m(a.events);for(V=a.next();!V.done;V=a.next()){var w=V.value;x=(w.tStartMs||0)+B;h=w.dDurationMs||0;if(w.id)e=String(w.id),V=yw7(this,w,x,h,e),G.push(V),this.X.set(e,V);else{w.wWinId?e=w.wWinId.toString():(e="_"+ER++,V=yw7(this,w,x,h,e),G.push(V),this.X.set(e,V));V=G;var K=w;h===0&&(h=5E3);
w=this.X.get(e);var l=!!K.aAppend,k=l?6:5,N=K.segs,d=null;K.pPenId&&(d=this.j.get(K.pPenId));for(K=0;K<N.length;K++){var C=N[K],z=C.utf8;if(z){var p=C.tOffsetMs||0,O=null;C.pPenId&&(O=this.j.get(C.pPenId));if((w.params.xb!=null?w.params.xb:w.j.length>1?1:0)===2&&l&&z==="\n")continue;C=null;var b=[],c;if(c=O&&O.Bx===1){c=N;var H=K;if(H+3>=c.length||!c[H+1].pPenId||!c[H+2].pPenId||!c[H+3].pPenId)c=!1;else{var R=c[H+1].pPenId;(R=this.j.get(R))&&R.Bx&&R.Bx===2?(R=c[H+2].pPenId,R=this.j.get(R),!R||!R.Bx||
R.Bx<3?c=!1:(R=c[H+3].pPenId,c=(R=this.j.get(R))&&R.Bx&&R.Bx===2?!0:!1)):c=!1}}if(c)p=N[K+1].utf8,C=N[K+3].utf8,c=N[K+2].utf8,H=this.j.get(N[K+2].pPenId),z=piW(z,p,c,C,H),C=new p3(x,h,k,e,z,l,O),K+=3;else{if(z.indexOf("<")>-1){var q=void 0;b=O;c=d;H=x;R=h;var A=p,J=k,xB=l,Wz=[],GK=g.JN("<html>"+z+"</html>");if(!GK.getElementsByTagName("parsererror").length&&((q=GK.firstChild)==null?0:q.childNodes.length))for(q=g.m(GK.firstChild.childNodes),GK=q.next();!GK.done;GK=q.next()){GK=GK.value;var Q=void 0,
M=void 0,I=(M=(Q=GK.textContent)==null?void 0:Q.replace(/\n/g,""))!=null?M:"";if(GK.nodeType!==3||I&&I.match(/^ *$/)==null){Q={};Object.assign(Q,b||c);M=void 0;switch((M=GK)==null?void 0:M.tagName){case "b":Q.bold=!0;break;case "i":Q.italic=!0;break;case "u":Q.underline=!0}Wz.push(new p3(H+A,R-A,J,w.id,I,xB,Q))}}b=Wz}b.length||(b=[new p3(x+p,h-p,k,w.id,z,l,O||d)])}if(b.length)for(l=g.m(b),O=l.next();!O.done;O=l.next())O=O.value,V.push(O),w.j.push(O);else C&&(V.push(C),w.j.push(C))}l=!0}}}B=G}else B=
[];return B};g.t(DL,g.Up);DL.prototype.Jt=function(G,B,a){vj3(this.videoData.videoId,G.vssId,a.yR)};
DL.prototype.Fp=function(G){if(this.audioTrack)for(var B=g.m(this.audioTrack.captionTracks),a=B.next();!a.done;a=B.next())g.pv(this.X,a.value);G.gJ()};g.t(SC,kq);SC.prototype.g0=function(G){var B=this.X.j;kq.prototype.g0.call(this,G);for(G=G.length;G<B.length;G++){var a=B[G];if(h&&a.j===x)var V=h;else{V={};Object.assign(V,a.j);Object.assign(V,KLW);var x=a.j;var h=V}MHW(this,a,V)}};
var KLW={N1H:!0};g.t(RT,goh);RT.prototype.G=function(G,B,a,V,x){if(a<V){var h="_"+ER++;a=a/1E3-this.L;V=V/1E3-this.L;G=new OR(a,V-a,5,h,{textAlign:0,T4:0,Uy:B*2.5,EC:G*5.33});x=new p3(a,V-a,5,h,x);this.X.push(G);this.X.push(x)}};
g.t($q,UR);$q.prototype.QN=function(G){G=new RT(G,G.byteLength,this.X);if(cwW(G)){for(;G.byteOffset<G.j.byteLength;)for(G.version===0?G.C=rh(G)*(1E3/45):G.version===1&&(G.C=rh(G)*4294967296+rh(G)),G.B=ZL(G);G.B>0;G.B--){var B=ZL(G),a=ZL(G),V=ZL(G);B&4&&(B&3)===this.track&&(this.track===0||this.track===1)&&(B=this.j,B.j.push({time:G.C,type:this.track,Iv:a,UP:V,order:B.j.length}))}e2a(this.j,G);return G.X}return[]};
$q.prototype.reset=function(){this.j.clear()};g.t(XH,kq);g.W=XH.prototype;g.W.iO=function(){g.PG(this.Er)};
g.W.NCN=function(){g.WC(this.element,"ytp-rollup-mode");this.wd(this.wO,!0)};
g.W.jG=function(){return this.C?this.zH:this.Y};
g.W.FX=function(){return this.C?this.Y:this.zH};
g.W.wd=function(G,B){this.wO=G;if(this.X.params.Xa){for(var a=0,V=0;V<this.W.length&&a<G.length;V++)this.W[V]===G[a]&&a++;a>0&&a<G.length&&(G=this.W.concat(G.slice(a)));this.QW=this.zH;this.Y=this.zH=0;kq.prototype.wd.call(this,G);vok(this,B)}kq.prototype.wd.call(this,G)};D_3.prototype.unload=function(){this.zW!=null&&(this.T.removeEventListener("sabrCaptionsDataLoaded",this.zW),this.zW=null);this.Pf=[];this.T.publish("sabrCaptionsBufferedRangesUpdated",this.Pf)};
D_3.prototype.mq=function(G){return{formatId:g.My(G.info.j.info,this.SE),AX:G.info.AX+(this.SE?0:1),startTimeMs:G.info.Sn*1E3,durationMs:G.info.L*1E3}};g.t(rw2,g.Up);g.W=rw2.prototype;g.W.Jt=function(G,B,a){this.Kc();B=G.getId();B=B!=null&&B in this.j.j?this.j.j[B]:null;B||(B=G.languageCode,B=this.j.isManifestless?XiJ(this,B,"386"):XiJ(this,B));B&&(this.C=G,this.L=B,Zal(this.W,a),this.T.publish("sabrCaptionsTrackChanged",g.My(B.info,this.j.SE)))};
g.W.Fp=function(G){var B=this.j.isManifestless?$_C(this,"386"):$_C(this);B=g.m(B);for(var a=B.next();!a.done;a=B.next())g.pv(this.X,a.value);G.gJ()};
g.W.Kc=function(){this.C&&(this.C=this.L=null,this.W.unload(),this.T.publish("sabrCaptionsTrackChanged",null))};
g.W.i9=function(){return""};
g.W.eX=function(){this.T.KD("captions")};g.t(qB,UR);
qB.prototype.QN=function(G,B){var a=[];G=G.split(l4k);for(var V=1;V<G.length;V++){var x=G[V],h=B;if(x!==""&&!k5W.test(x)){var e=Npk.exec(x);if(e&&e.length>=4){var w=QLJ(e[1]),K=QLJ(e[2])-w;w+=h;var l=(e=e[3])?e.split(" "):[];e={};var k=null;var N="";var d=null,C="";l=g.m(l);for(var z=l.next();!z.done;z=l.next())if(z=z.value.split(":"),z.length===2){var p=z[1];switch(z[0]){case "line":z=p.split(",");z[0].endsWith("%")&&(k=z[0],e.EC=Number.parseInt(k,10),z.length===2&&(N=z[1].trim()));break;case "position":z=
p.split(",");d=z[0];e.Uy=Number.parseInt(d,10);z.length===2&&(C=z[1].trim());break;case "align":switch(p){case "start":e.textAlign=0;break;case "middle":e.textAlign=2;break;case "end":e.textAlign=1}}}k||N||(N="end");if(!d)switch(e.textAlign){case 0:e.Uy=0;break;case 1:e.Uy=100;break;case 2:e.Uy=50}if(e.textAlign!=null){k=0;switch(N){case "center":k+=3;break;case "end":k+=6;break;default:k+=0}switch(C){case "line-left":k+=0;break;case "center":k+=1;break;case "line-right":k+=2;break;default:switch(e.textAlign){case 0:k+=
0;break;case 2:k+=1;break;case 1:k+=2}}N=k<0||k>8?7:k;e.T4=N}x=x.substring(Npk.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");C=e;e=x;x={};if(e.indexOf("<")<0&&e.indexOf("&")<0)h=LEl(w,K,5,C),K=new p3(w,K,5,h.id,e,!1,g.yw(x)?void 0:x),a.push(h),a.push(K),h.j.push(K);else for(N=e.split(dHk),N.length===1?(e=5,C=LEl(w,K,e,C)):(k=e=6,C=Object.assign({pL:32},C),C=new OR(w,K,k,"_"+ER++,C)),a.push(C),k=w,d=0;d<N.length;d++)l=N[d],d%2===0?(z=g.JN("<html>"+l+"</html>"),z.getElementsByTagName("parsererror").length?
(p=z.createElement("span"),p.appendChild(z.createTextNode(l))):p=z.firstChild,ums(this,k,K-(k-w),e,C,d>0,p,x,a)):k=QLJ(l)+h}Npk.lastIndex=0}}return a};
var k5W=/^NOTE/,l4k=/(?:\r\n|\r|\n){2,}/,Npk=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),dHk=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.RH.Zk(qB,{QN:"wvppt"});g.t(ut,g.r);
ut.prototype.QN=function(G,B,a,V){V=V||0;a=sL$(this,G,a||0);G=[];try{for(var x=g.m(a),h=x.next();!h.done;h=x.next()){var e=h.value,w=e.trackData,K=e.GX;if(typeof w!=="string"){a=G;var l=a.concat,k=B,N=w,d=K,C=V;if(!nol(N))throw Error("Invalid binary caption track data");this.j||(this.j=new $q(C,k));var z=this.j.QN(N,d);var p=l.call(a,z)}else{if(w.substring(0,6)==="WEBVTT"){a=G;var O=a.concat;this.j||(this.j=new qB);var b=this.j.QN(w,K);Math.random()<.01&&g.Zb(Error("Deprecated subtitles format in web player: WebVTT"));var c=
O.call(a,b)}else{a=G;var H=a.concat;a:{k=B;if(w[0]==="{")try{this.j||(this.j=new He(FEW(k)));var R=this.j.QN(w,K);break a}catch(GK){g.RA(GK);R=[];break a}var q=g.JN(w);if(!q||!q.firstChild){var A=Error("Invalid caption track data");A.params=w;throw A;}if(q.firstChild.tagName==="timedtext"){if(Number(q.firstChild.getAttribute("format"))===3){N=q;this.j||(this.j=new jC(FEW(k),this.md));R=this.j.QN(N,K);break a}var J=Error("Unsupported subtitles format in web player (Format2)");J.params=w;throw J;}if(q.firstChild.tagName===
"transcript"){var xB=Error("Unsupported subtitles format in web player (Format1)");xB.params=w;throw xB;}var Wz=Error("Invalid caption track data");Wz.params=w;throw Wz;}c=H.call(a,R)}p=c}G=p}return G}catch(GK){return this.logger.j(187101178,"Captions parsing failed: "+GK.message+". "),this.clear(),[]}};
ut.prototype.clear=function(){this.j&&this.j.dispose();this.j=null};
ut.prototype.reset=function(){this.j&&this.j.reset()};
ut.prototype.yb=function(){g.r.prototype.yb.call(this);this.clear()};var it={windowColor:"#080808",windowOpacity:0,textAlign:2,T4:7,Uy:50,EC:100,isDefault:!0,HD:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.t(Qv,g.go);g.W=Qv.prototype;g.W.yb=function(){if(this.B||this.Zx){var G=this.T.Zc();G&&!G.TH()&&G.F7()}else WLl(this,!1);g.go.prototype.yb.call(this)};
g.W.jY=function(){return this.md.S("html5_honor_caption_availabilities_in_audio_track")&&this.G!=="LIVE"&&this.G!=="SABR_LIVE"};
g.W.Jg=function(){if(this.Ur)return this.B||this.Zx;var G=this.getAudioTrack();if(this.jY()){if(!G.captionTracks.length)return!1;if(!this.j)return!0}G=c$s(G,g.YF(this.md));return G==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:G==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?L3(this):ial(this)||L3(this)?!0:PfC(this)};
g.W.load=function(){g.go.prototype.load.call(this);this.Y=this.getAudioTrack();if(this.j)this.X&&(this.MB.clear(),this.B?Ms2(this,!0):this.player.getPresentingPlayerType()!==3&&this.j.Jt(this.X,"json3",this.QW),this.B||this.Zx||FH(this)||this.player.Ff("captionschanged",g.C$(this.X)));else{var G;this.G==="OFFLINE"?G=new DL(this.player,this.videoData,this.getAudioTrack()):this.G==="SABR_LIVE"?G=new rw2(this.videoData.j,this.player):this.G==="LIVE"?G=new lt(this.videoData.j,this.player):this.G==="INNERTUBE"?
G=new g.Op(this.player,this.videoData,this.getAudioTrack()):G=new g.jA(this.player,this.videoData.xF,this.videoData.videoId,g.Ucg(this.videoData),this.videoData.bF,this.videoData.eventId);this.j=G;g.X(this,this.j);this.j.Fp(this.QW)}};
g.W.unload=function(){this.B&&this.X?Ms2(this,!1):(this.SJ&&g.oX(this.SJ),this.player.KD("captions"),this.LN=[],this.j&&this.j.Kc(),this.MB.clear(),this.zH&&this.player.z1(this.zH),this.xE());g.go.prototype.unload.call(this);this.player.Bm();this.player.Ff("captionschanged",{})};
g.W.create=function(){this.Jg()&&this.load();var G;a:{var B,a,V;if(this.md.S("web_player_nitrate_promo_tooltip")&&((B=this.videoData.getPlayerResponse())==null?0:(a=B.captions)==null?0:(V=a.playerCaptionsTracklistRenderer)==null?0:V.enableTouchCaptionsNitrate)){var x,h;if(B=(G=this.videoData.getPlayerResponse())==null?void 0:(x=G.captions)==null?void 0:(h=x.playerCaptionsTracklistRenderer)==null?void 0:h.captionTracks)for(G=g.m(B),x=G.next();!x.done;x=G.next())if(x=x.value,x.kind==="asr"&&x.languageCode===
"en"){G=!0;break a}}G=!1}G&&this.T.publish("showpromotooltip",this.W.element)};
g.W.gJ=function(){var G=c$s(this.player.getAudioTrack(),g.YF(this.md));var B=G==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?sR(this,this.V):G==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&L3(this)?Tt(this):ial(this)||this.V||PfC(this)?sR(this,this.V):L3(this)?Tt(this):null;if(this.B||this.Zx){var a=g.ha(this.j.X,!0);G=[];for(var V=0;V<a.length;V++){var x=a[V],h=g.M6("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.dt(x));h.setAttribute("srclang",g.zk(x));h.setAttribute("id",x.toString());
this.Zx||h.setAttribute("src",this.j.i9(x,"vtt"));x===B&&h.setAttribute("default","1");G.push(h)}B=this.T.Zc();B.Oz(G);G=B.dO();this.Yf&&this.GH.K(G.textTracks,"change",this.Ky1)}else!this.X&&B&&Yq(this,B),this.player.Ff("onCaptionsTrackListChanged"),this.player.qD("onApiChange")};
g.W.Ky1=function(){for(var G=this.T.Zc().dO().textTracks,B=null,a=0;a<G.length;a++)if(G[a].mode==="showing")a:{B=g.ha(this.j.X,!0);for(var V=0;V<B.length;V++)if(B[V].toString()===G[a].id){B=B[V];break a}B=null}(this.loaded?this.X:null)!==B&&Yq(this,B,!0)};
g.W.dLX=function(){!this.X&&this.B||this.unload()};
g.W.yR=function(G,B,a,V){if(G){var x;Bps(this,(x=this.X)!=null?x:void 0);this.j.FR()&&(this.LN=[],this.T.KD("captions"),wh(this.Qb),this.MB.reset());if(this.videoData.dC){var h;a=((h=a)!=null?h:0)+this.videoData.dC}G=this.MB.QN(G,B,a,V);if(this.Vb)for(B=g.m(G),a=B.next();!a.done;a=B.next())a=a.value,a.C=this.videoData.clientPlaybackNonce,a.Y1=this.videoData.dC;B=!this.md.S("html5_keep_caption_data_after_seek")&&(this.G==="LIVE"||this.G==="SABR_LIVE");this.player.z1(G,void 0,B);!this.V||this.Zx||FH(this)||
g.yI(this.md)||g.R$(this.md)||g.rv(this.md)||this.md.Zx==="shortspage"||this.player.isInline()||(g.oX(this.SJ),G=Oas({T4:0,Uy:5,EC:5,Xa:2,textAlign:0,eK:0,lang:"en"}),this.qB=[G],B=["Click "," for settings"],this.eJ||(a=new g.le(g.nr()),g.X(this,a),this.eJ=a.element),a=G.end-G.start,(V=g.dt(this.X))&&this.qB.push(new p3(G.start,a,0,G.id,V)),this.qB.push(new p3(G.start,a,0,G.id,B[0]),new p3(G.start,a,0,G.id,this.eJ,!0),new p3(G.start,a,0,G.id,B[1],!0)),this.player.z1(this.qB),g.iC(this.SJ));!this.V||
this.Zx||FH(this)||(g.YF(this.md)?JH(this,!0):AH(this,!0),this.Y&&(this.Y.G=this.X),this.player.Bm());this.V=!1}};
g.W.onCueRangeEnter=function(G){this.LN.push(G);wh(this.Qb)};
g.W.onCueRangeExit=function(G){g.PW(this.LN,G);this.j instanceof lt&&this.j.W&&this.player.FO([G]);wh(this.Qb)};
g.W.getCaptionWindowContainerId=function(){return this.W.element.id};
g.W.EaN=function(){e$a(this,this.qB);this.qB=null};
g.W.EO=function(){var G=this;if(!this.fh||!this.B){this.Qb.stop();g.JDB(this.Er);this.LN.sort(g.xu);var B=this.LN;if(this.zH){var a=g.wb(B,function(h){return this.zH.indexOf(h)===-1},this);
a.length&&(B=a)}B=g.m(B);for(a=B.next();!a.done;a=B.next())VU7(this,a.value);B=g.m(Object.entries(this.HS));var V=B.next();for(a={};!V.done;a={m_:void 0,Hs:void 0},V=B.next()){var x=g.m(V.value);V=x.next().value;x=x.next().value;a.m_=V;a.Hs=x;this.Er[a.m_]?(a.Hs.element.parentNode||(a.Hs instanceof XH||a.Hs instanceof SC||g.gU(this.HS,function(h){return function(e,w){w!==h.m_&&e.X.params.T4===h.Hs.X.params.T4&&e.X.params.Uy===h.Hs.X.params.Uy&&e.X.params.EC===h.Hs.X.params.EC&&(e.dispose(),delete G.HS[w]);
return w===h.m_}}(a),this),this.W.element.appendChild(a.Hs.element)),a.Hs.wd(this.Er[a.m_])):(a.Hs.dispose(),delete this.HS[a.m_])}}};
g.W.UqX=function(){Awf(this,{},!0);this.player.Ff("captionssettingschanged")};
g.W.vfN=function(){var G=it.HD;G={background:G.background,backgroundOpacity:G.backgroundOpacity,charEdgeStyle:G.charEdgeStyle,color:G.color,fontFamily:G.fontFamily,fontSizeIncrement:G.fontSizeIncrement,fontStyle:G.bold&&G.italic?3:G.bold?1:G.italic?2:0,textOpacity:G.textOpacity,windowColor:it.windowColor,windowOpacity:it.windowOpacity};var B=r$a()||{};B.background!=null&&(G.background=B.background);B.backgroundOverride!=null&&(G.backgroundOverride=B.backgroundOverride);B.backgroundOpacity!=null&&
(G.backgroundOpacity=B.backgroundOpacity);B.backgroundOpacityOverride!=null&&(G.backgroundOpacityOverride=B.backgroundOpacityOverride);B.charEdgeStyle!=null&&(G.charEdgeStyle=B.charEdgeStyle);B.charEdgeStyleOverride!=null&&(G.charEdgeStyleOverride=B.charEdgeStyleOverride);B.color!=null&&(G.color=B.color);B.colorOverride!=null&&(G.colorOverride=B.colorOverride);B.fontFamily!=null&&(G.fontFamily=B.fontFamily);B.fontFamilyOverride!=null&&(G.fontFamilyOverride=B.fontFamilyOverride);B.fontSizeIncrement!=
null&&(G.fontSizeIncrement=B.fontSizeIncrement);B.fontSizeIncrementOverride!=null&&(G.fontSizeIncrementOverride=B.fontSizeIncrementOverride);B.fontStyle!=null&&(G.fontStyle=B.fontStyle);B.fontStyleOverride!=null&&(G.fontStyleOverride=B.fontStyleOverride);B.textOpacity!=null&&(G.textOpacity=B.textOpacity);B.textOpacityOverride!=null&&(G.textOpacityOverride=B.textOpacityOverride);B.windowColor!=null&&(G.windowColor=B.windowColor);B.windowColorOverride!=null&&(G.windowColorOverride=B.windowColorOverride);
B.windowOpacity!=null&&(G.windowOpacity=B.windowOpacity);B.windowOpacityOverride!=null&&(G.windowOpacityOverride=B.windowOpacityOverride);return G};
g.W.Nt=function(G,B){var a={};Object.assign(a,r$a());Object.assign(a,G);Awf(this,a,B);this.player.Ff("captionssettingschanged")};
g.W.xE=function(){!this.B&&this.loaded&&(g.t$(this.HS,function(G,B){G.dispose();delete this.HS[B]},this),this.EO())};
g.W.dJ=function(G,B){switch(G){case "fontSize":if(isNaN(B))break;G=g.eH(B,-2,4);this.Nt({fontSizeIncrement:G});return G;case "reload":B&&!this.B&&Yq(this,this.X,!0);break;case "stickyLoading":B!==void 0&&this.md.W&&(g.YF(this.md)?JH(this,!!B):AH(this,!!B));break;case "track":return h$7(this,B);case "tracklist":return this.j?g.br(g.ha(this.j.X,!(!B||!B.includeAsr)),function(a){return g.C$(a)}):[];
case "translationLanguages":return this.j?this.j.B.map(function(a){return Object.assign({},a)}):[];
case "sampleSubtitles":this.B||B===void 0||WLl(this,!!B);break;case "sampleSubtitlesCustomized":this.B||WLl(this,!!B,B);break;case "recommendedTranslationLanguages":return g.uD();case "defaultTranslationSourceTrackIndices":return this.j?this.j.V:[]}};
g.W.getOptions=function(){var G="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.md.W&&G.push("stickyLoading");return G};
g.W.G9=function(){var G=this.X;if(this.T.Eo("captions")){if(this.md.S("html5_modify_caption_vss_logging")){var B;return(G=(B=this.videoData.Bj)!=null?B:null)?{cc:g.uZK(G)}:{}}if(G)return B=G.vssId,G.translationLanguage&&B&&(B="t"+B+"."+g.zk(G)),{cc:B}}return{}};
g.W.mLf=function(){this.isSubtitlesOn()?(g.YF(this.md)?JH(this,!1):AH(this,!1),Bps(this),this.md.S("html5_report_caption_format_change")?Yq(this,null,!0):(this.unload(),L3(this,!0)&&Yq(this,Tt(this),!1))):this.Az()};
g.W.Az=function(){var G=FH(this)||!this.X?sR(this,!0):this.X;this.md.S("html5_report_caption_format_intent")&&G&&this.jK(G.vssId,"m");this.isSubtitlesOn()||Yq(this,FH(this)||!this.X?sR(this,!0):this.X,!0)};
g.W.isSubtitlesOn=function(){return!!this.loaded&&!!this.X&&!FH(this)};
g.W.Q0d=function(){var G=FH(this);L3(this,G)?Yq(this,this.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.jY()&&(this.V=!1,this.X=null,this.j&&(this.j.dispose(),this.j=null)),this.Jg()&&(G?Yq(this,sR(this,!1),!1):this.load()))};
g.W.W7=function(G){G&&(this.XJ={top:G.top,right:G.right,bottom:G.bottom,left:G.left,width:1-G.left-G.right,height:1-G.top-G.bottom},this.W.element.style.top=this.XJ.top*100+"%",this.W.element.style.left=this.XJ.left*100+"%",this.W.element.style.width=this.XJ.width*100+"%",this.W.element.style.height=this.XJ.height*100+"%",this.W.element.style.position="absolute",G=xHC(this))&&(this.W.element.style.width=G.width+"px",this.W.element.style.height=G.height+"px")};
g.W.onVideoDataChange=function(G,B){G==="newdata"&&(this.videoData=B,this.loaded&&this.unload(),this.V=!1,this.X=null,this.j&&(this.j.dispose(),this.j=null,this.player.Ff("captionschanged",{})),this.Jg()&&this.load())};
g.W.getAudioTrack=function(){return this.Vb&&this.player.getPresentingPlayerType()===2?this.videoData.M9:this.player.getAudioTrack()};
g.W.yiN=function(){var G=this.T.Zc();G&&!G.TH()&&G.F7();this.T.isFullscreen()?(this.B=this.Ur=!0,this.loaded&&this.gJ()):(this.Ur=this.md.controlsType==="3",this.B=Jw9(this));Yq(this,this.X)};
g.W.e3=function(){var G,B,a,V=(G=this.videoData.getPlayerResponse())==null?void 0:(B=G.captions)==null?void 0:(a=B.playerCaptionsTracklistRenderer)==null?void 0:a.openTranscriptCommand;V&&this.player.pN("innertubeCommand",V)};
g.W.GV=function(G,B,a){var V=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,x="";G&&(x=G.vssId,x=x.replace(V,""));var h="";G&&G.getId()&&(h=G.getId()||"");G&&G.getXtags()&&(G=G.getXtags(),G=G.replace(V,""),h=h.concat(";"+G));this.T.GV(B?x:"",B?h:"",a)};
g.W.jK=function(G,B){G=(G||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");G.length>0&&this.T.jK(G,B)};
g.W.eX=function(){this.j&&this.j.eX()};
g.RH.Zk(Qv,{EO:"smucd"});g.Is("captions",Qv);})(_yt_player);
