(function(g){var window=this;'use strict';var Sm=function(G,B){g.T.call(this,{Z:"button",bL:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],N:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},D:[{Z:"svg",N:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},D:[{Z:"g",N:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},D:[{Z:"g",N:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
D:[{Z:"path",N:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.T=G;this.listen("click",this.onClick,this);this.updateValue("title",g.jX(G,"Expand","i"));this.update({"data-title-no-tooltip":"Expand"});this.addOnDisposeCallback(g.Oc(B.G1(),this.element))},Pcl=function(G){g.T.call(this,
{Z:"div",
J:"ytp-miniplayer-ui"});this.L=!1;this.player=G;this.K(G,"minimized",this.qH);this.K(G,"onStateChange",this.E3N);this.K(G,"documentpictureinpicturechange",this.UQB)},oHW=function(G,B){g.Km(G.player.getRootNode(),"ytp-player-minimized",B)},MJ9=function(G){g.go.call(this,G);
this.X=new g.Zh(this);this.j=new Pcl(this.player);this.j.hide();g.SX(this.player,this.j.element,4);G.isMinimized()&&(this.load(),g.Km(G.getRootNode(),"ytp-player-minimized",!0))};
g.t(Sm,g.T);Sm.prototype.onClick=function(){this.T.pN("onExpandMiniplayer")};g.t(Pcl,g.T);g.W=Pcl.prototype;
g.W.show=function(){this.j=new g.F7(this.uM,null,this);this.j.start();if(!this.L){this.tooltip=new g.nk(this.player,this);g.X(this,this.tooltip);g.SX(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.wC=new g.id(this.player);g.X(this,this.wC);this.progressBar=new g.QO(this.player,this);g.X(this,this.progressBar);g.SX(this.player,this.progressBar.element,4);this.X=new g.T({Z:"div",J:"ytp-miniplayer-scrim"});g.X(this,this.X);this.X.iL(this.element);this.K(this.X.element,"click",this.dP);
var G=new g.T({Z:"button",bL:["ytp-miniplayer-close-button","ytp-button"],N:{"aria-label":"Close"},D:[g.UX()]});g.X(this,G);G.iL(this.X.element);this.K(G.element,"click",this.dk);G=new Sm(this.player,this);g.X(this,G);G.iL(this.X.element);this.C=new g.T({Z:"div",J:"ytp-miniplayer-controls"});g.X(this,this.C);this.C.iL(this.X.element);this.K(this.C.element,"click",this.dP);var B=new g.T({Z:"div",J:"ytp-miniplayer-button-container"});g.X(this,B);B.iL(this.C.element);G=new g.T({Z:"div",J:"ytp-miniplayer-play-button-container"});
g.X(this,G);G.iL(this.C.element);var a=new g.T({Z:"div",J:"ytp-miniplayer-button-container"});g.X(this,a);a.iL(this.C.element);this.V=new g.rq(this.player,this,!1);g.X(this,this.V);this.V.iL(B.element);B=new g.ZV(this.player,this);g.X(this,B);B.iL(G.element);this.nextButton=new g.rq(this.player,this,!0);g.X(this,this.nextButton);this.nextButton.iL(a.element);this.W=new g.g7(this.player,this,0);g.X(this,this.W);this.W.iL(this.X.element);this.G=new g.T({Z:"div",J:"ytp-miniplayer-buttons"});g.X(this,
this.G);g.SX(this.player,this.G.element,4);G=new g.T({Z:"button",bL:["ytp-miniplayer-close-button","ytp-button"],N:{"aria-label":"Close"},D:[g.UX()]});g.X(this,G);G.iL(this.G.element);this.K(G.element,"click",this.dk);G=new g.T({Z:"button",bL:["ytp-miniplayer-replay-button","ytp-button"],N:{"aria-label":"Close"},D:[g.cr()]});g.X(this,G);G.iL(this.G.element);this.K(G.element,"click",this.n_b);G=new Sm(this.player,this);g.X(this,G);G.iL(this.G.element);this.K(this.player,"presentingplayerstatechange",
this.qK);this.K(this.player,"appresize",this.Df);this.K(this.player,"fullscreentoggled",this.Df);this.Df();this.L=!0}this.player.getPlayerState()!==0&&g.T.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.W.hide=function(){this.j&&(this.j.dispose(),this.j=void 0);g.T.prototype.hide.call(this);this.player.isMinimized()||(this.L&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.W.yb=function(){this.j&&(this.j.dispose(),this.j=void 0);g.T.prototype.yb.call(this)};
g.W.dk=function(){this.player.S("kevlar_watch_while_v2")||this.player.stopVideo();this.player.pN("onCloseMiniplayer")};
g.W.n_b=function(){this.player.playVideo()};
g.W.dP=function(G){if(G.target===this.X.element||G.target===this.C.element)this.player.getPlayerStateObject().isOrWillBePlaying()?this.player.pauseVideo():this.player.playVideo()};
g.W.qH=function(){oHW(this,this.player.isMinimized())};
g.W.UQB=function(){oHW(this,this.player.l2());g.Km(this.player.getRootNode(),"ytp-player-document-picture-in-picture",this.player.l2())};
g.W.OA=function(){this.progressBar.BC();this.W.BC()};
g.W.uM=function(){this.OA();this.j&&this.j.start()};
g.W.qK=function(G){g.F(G.state,32)&&this.tooltip.hide()};
g.W.Df=function(){var G=this.player.g1().getPlayerSize().width;g.mQ9(this.progressBar,0,G,!1);g.LM(this.progressBar)};
g.W.E3N=function(G){this.player.isMinimized()&&(G===0?this.hide():this.show())};
g.W.G1=function(){return this.tooltip};
g.W.xp=function(G,B,a,V,x){var h=0,e=0,w=0,K=g.UK(G);V=B&&(g.x$(B,"ytp-prev-button")||g.x$(B,"ytp-next-button"));if(B){a=g.x$(B,"ytp-play-button");var l=g.x$(B,"ytp-miniplayer-expand-watch-page-button");V?h=w=12:a?(B=g.gx(B,this.element),w=B.x,h=B.y-12):l&&(w=g.x$(B,"ytp-miniplayer-button-top-left"),h=g.gx(B,this.element),B=g.UK(B),w?(w=8,h=h.y+40):(w=h.x-K.width+B.width,h=h.y-20))}else w=a-K.width/2,e=25+(x||0);B=this.player.g1().getPlayerSize();x=h+(x||0);K=g.eH(w,0,B.width-K.width-12);x?(G.style.top=
x+"px",G.style.bottom=""):(G.style.top="",G.style.bottom=e+"px");G.style.left=K+"px";e=g.x$(G,"ytp-preview");G.style.visibility=V&&e&&B.height<225?"hidden":""};g.t(MJ9,g.go);g.W=MJ9.prototype;g.W.onVideoDataChange=function(){if(this.player.getVideoData()){var G=this.player.getVideoAspectRatio(),B=16/9;G=G>B+.1||G<B-.1;g.Km(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",G)}};
g.W.create=function(){g.go.prototype.create.call(this);this.X.K(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.W.v6=function(){return!1};
g.W.load=function(){this.player.hideControls();this.j.show()};
g.W.unload=function(){this.player.showControls();this.j.hide()};g.Is("miniplayer",MJ9);})(_yt_player);
